packages/access/src/capabilities/upload.js, packages/access/test/capabilities/upload.test.js, packages/access/test/helpers/utils.js
@gozala should `root` be the root CID of the data, not a CAR CID? This is how it's implemented AFAIK. Or were you thinking it was the CID of the CAR that has the root data CID?
This PR switches `root` to allow _any_ CID, not just a CAR CID.
Also, for a separate PR, maybe neither of these fields should be optional. Like, an "upload" should always have a data root CID and be present in at least 1 shard?
=> fix: upload/add capability root validation

packages/access/src/capabilities/upload.js
Same as https://github.com/web3-storage/w3protocol/pull/169 but for upload capabilities. Did also a quick look at generated types in other capabilities and they look fine.
=> fix: workaround for ts bug in upload capabilities

spec/capabilities.md, spec/services.md
This is a start at a reference doc for all the capabilities defined in this repo. 
There's also a stub for a "services.md" that will have details about the response values and possible error types for each capability handler.
So far, I've got `store/add` and `store/remove` covered, plus some intro context material.
@alanshaw, could you give some early 👀 to make sure the format works for you, and that you have all the info here that you would expect?
closes #172
=> chore: add capabilities.md with cap reference docs

packages/upload-client/README.md, packages/upload-client/src/index.js, packages/upload-client/src/sharding.js, packages/upload-client/src/types.ts, packages/upload-client/test/index.test.js
Bubbles up the shard size option so `uploadFile` and `uploadDirectory` can set it.
=> feat: allow custom shard size

packages/access-client/src/capabilities/store.js, packages/access-client/src/capabilities/upload.js, packages/access-client/test/capabilities/upload.test.js
Adds support for list pagination in `store/list` and `upload/list`.
Relevant notes on decisions made:
- unfortunately, Databases like DynamoDB does not support pagination by just giving `pageNumber` and `size`. Aiming to have something generic (that works in DynamoDB, but also other DBs), chosen approach is to rely on `cursor` and `size` .
- at first, attempted to make `cursor` a Link property of the capability. And it worked well for `store/list`, but then I got to use cases (`upload/list` for instance) where it cannot be a link. This is because Upload Table primary key contains `${dataCid}#${carCid}` to be unique. So, in this case that is the cursor we need to have. There might be other kind of use cases, so having this as string is really the most flexible approach to support …
=> feat: add support for list pagination in list capability invocations

packages/upload-client/README.md, packages/upload-client/src/index.js
Documented as `Store` in the README and this it aligns better with the capability name. I had it as `Storage` for a while but changed it to `Store`...but missed this instance 🤦‍♂️
=> fix: store export

packages/upload-client/README.md, packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/upload-client/test/index.test.js
I keep getting this wrong, to the extent that I even documented it this way in the README.
I think `on[noun][verb]` aligns better with DOM event callbacks e.g. `onMouseClick`.
=> refactor!: rename callback

packages/access-client/src/stores/store-indexeddb.js, packages/access-client/test/stores/store-indexeddb.browser.test.js
This `create` function is kinda useless except for in tests right now because as soon as you use it for the second time it blows away the existing data.
=> feat!: rename static indexeddb store method create to open

packages/upload-client/src/types.ts
It now always returns an array.
=> fix: list response results return type

packages/access-client/src/stores/store-indexeddb.js, packages/access-client/src/stores/types.ts, packages/access-client/test/stores/store-indexeddb.browser.test.js
You can't store a CID instance in IndexedDB.
=> fix: round trip delegations in IndexedDB store

.github/workflows/access-api.yml, .github/workflows/access-client.yml, .github/workflows/upload-client.yml, package.json, packages/access-api/package.json, packages/access-api/scripts/migrate.js, packages/access-api/test/account-recover.test.js, packages/access-api/test/voucher-redeem.test.js, packages/access-client/package.json, packages/access-ws/package.json, packages/upload-client/package.json, packages/wallet/package.json, pnpm-lock.yaml
I was concerned about missing deps but turns out we dont have any, bundlephobia cannot handle export maps so lots of ipld and ucanto stuff fail to be resolved because they dont have a `main` in package.json.
- update typescript to latest 0.9.4
=> chore: add depcheck to all packages and update deps

.github/release-please-manifest.json
Motivation:
* https://github.com/web3-storage/w3protocol/issues/80#issuecomment-1331443102
* trying to get release-please-action to generate a release PR for packages/capabilities
* I would have expected it in this action, but there was [an error](https://github.com/web3-storage/w3protocol/actions/runs/3587365143/jobs/6037622712#step:2:44)
```
Expected 5 releases, only found 4
⚠ Missing 1 paths: packages/capabilities
⚠ No version for path packages/capabilities
```
Theory:
* maybe these errors are because I hadn't added this package to the manifest?
=> add packages/capabilities to .github/release-please-manifest.json

packages/upload-client/README.md, packages/upload-client/src/types.ts, packages/upload-client/src/upload.js, packages/upload-client/test/helpers/car.js, packages/upload-client/test/helpers/random.js, packages/upload-client/test/index.test.js, packages/upload-client/test/store.test.js, packages/upload-client/test/upload.test.js
- update tests and types to handle upload/list items with a shards array property.
- update upload/add fn to return an UploadAddResponse as shards out may be more than shards in.
- update README
see also: https://github.com/web3-storage/upload-api/pull/56
=> feat!: upload/list items have a shards array property

packages/access-api/test/space-info.test.js, packages/capabilities/src/space.js
=> fix: fix Access API cannot get space/info #243

.github/release-please-config.json, .github/release-please-manifest.json, .github/workflows/manual.yml, .github/workflows/release.yml
Motivation:
* latest commit on main branch was failing release workflow [here](https://github.com/web3-storage/w3protocol/actions/runs/3621669639/jobs/6105393187#step:2:35)
* I think it's because the release-please config/manifest still referred to `package/wallet`, which this PR removes
* seems like logical followup to https://github.com/web3-storage/w3protocol/pull/248
=> fix: remove remaining references to packages/wallet

packages/access-api/src/utils/html.js
=> fix: add validation copy

package.json
I noticed earlier today that running `pnpm run docs` fails with a bunch of typescript errors unless you run `pnpm run build` first.
This just updates the `docs` npm script to `pnpm run build && typedoc --out docs`, so we'll always have build output to make typedoc happy.
<details>
<summary>error output if you don't build first</summary>
```
packages/access-client/src/agent.js:12:24 - error TS2307: Cannot find module '@web3-storage/capabilities/space' or its corresponding type declarations.
12 import * as Space from '@web3-storage/capabilities/space'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
packages/access-client/src/agent.js:13:26 - error TS2307: Cannot find module '@web3-storage/capabilities/voucher' or its corresponding type declarations.
13 import * as Voucher from …
```
=> chore: run `pnpm run build` before typedoc to avoid type errors

packages/access-client/package.json, packages/access-client/src/utils/json.js, packages/access-client/test/drivers/conf.node.test.js, pnpm-lock.yaml
Buffer has a toJSON implementation which is called before our replacer function when serialising. It's JSON form is an object like `{ type: 'Buffer, data: number[] }`.
This means it doesn't get identfied as $bytes, and does not get deserialised in the reviver. I think we'd rather have `Uint8Array` everywhere so this PR fixes it so that it gets revived as that.
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>
=> fix: handle Buffer serialization

packages/access-client/src/agent-data.js, packages/access-client/test/agent-data.test.js
Destructuring the `save` method of the passed store is causing problems when the store wants to access instance vars/methods.
=> fix: destructured save

packages/access-api/package.json, packages/access-api/src/bindings.d.ts, packages/access-api/src/config.js, packages/access-api/src/utils/context.js, packages/access-api/test/config.test.js, packages/access-api/test/helpers/context.js, packages/access-api/test/ucan.test.js, pnpm-lock.yaml
Motivation:
* https://github.com/web3-storage/w3protocol/issues/237
Notes
* This is intended to be safe to merge/deploy as is. The new functionality can be opted-into via env vars
* The ucanto server will only be constructed with an opts.id that is a signer `withDID(...)` iff `process.env.DID` is set to a DID
* If `process.env.DID` is unset, the ucanto server id signer will have a `did()` corresponding to `config.PRIVATE_KEY` (it will be a `did:key` of the corresponding public key)
* Before this PR, many tests of the access-api worker were configured implicitly via dotenv with whatever the `/.env.local` file happened to contain. I added a worker test that asserts functionality that is dependent on the details of the env vars, so I made an affordance for [tests to be able to configure the …
=> feat: access-api uses DID env variable when building its ucanto server id

packages/access-client/src/agent.js, packages/access-client/src/cli/cmd-whoami.js, packages/access-client/test/agent.test.js
By removing the side effect many methods that read data in memory no longer have to be async. I think this makes the API simplier.
I've added a _method_ that can be called to clean up expired delegations, which shifts the responsibility onto the user. Alternatively we could move the clean up into the methods that write delegations? Open to other suggestions.
resolves #219
=> refactor: sync delegations method

packages/upload-client/src/types.ts, packages/upload-client/src/upload.js, packages/upload-client/test/upload.test.js
needed by https://github.com/web3-storage/w3cli/pull/20 to find which shards to also remove when removing an upload
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>
=> feat: upload/remove returns removed item

packages/access-client/readme.md
This adds an About section with some context about the access-client and how it fits into the bigger picture.
It also adds some detail to the Usage section, which now has subsections for creating Agents & Spaces and registering Spaces with the access service.
Closes #251
=> chore: add about section & usage examples to access-client readme

packages/access-api/wrangler.toml
Motivation:
* enable the DID functionality in these environments
=> chore: add DID env var to access-api wrangler.toml for staging and production

packages/access-api/package.json, packages/access-client/package.json, packages/access-client/src/cli/cmd-create-space.js, packages/access-client/src/cli/index.js, packages/access-client/src/cli/utils.js, packages/access-ws/package.json, packages/capabilities/package.json, pnpm-lock.yaml
We removed service DID resolution from the agent so CLI needs to pass in the DID now.
=> fix: fix client cli service did resolve

packages/access-api/package.json, packages/access-api/src/config.js, packages/access-api/src/routes/raw.js, packages/access-api/test/config.test.js, packages/access-api/wrangler.toml, pnpm-lock.yaml
Motivation:
* https://github.com/web3-storage/w3protocol/issues/302
=> fix: access-api ctx.signer no longer uses env.DID. instead env.DID is only used for ucanto server id

packages/upload-client/README.md
Just a small update to the upload-client readme to point users at `w3up-client` unless they want to get into the weeds :)
Also adds a link to the access client docs in the agent creation section.
Closes #250
=> chore: add about section to upload-client readme & link to access docs

packages/access-api/src/routes/version.js
Motivation:
* `@web3-storage/access` cli expects to be able to fetch /version and pull the `did` property in order to create the ucanto Verifier that is used as the `aud` when signing ucans
* https://github.com/web3-storage/w3protocol/blob/main/packages/access-client/src/cli/utils.js#L28
* before this change, that `did` property came from `ctx.signer`, which will have a `did:key`.
* but since https://github.com/web3-storage/w3protocol/pull/303 , the verifier used in the ucanto server for upload-api is actually different than `ctx.signer.did()`. So this PR makes it so /version `did` property actually comes from `ctx.config.ucantoServerId`
* it also adds a new key to that endpoint, `signer`, which is the public key of the signer (which now can be different than the `DID` of the ucanto …
=> feat: access-api version route sets did=ucantoServerId and adds a signer prop

packages/access-api/src/routes/version.js
Reverts web3-storage/w3protocol#305
Motivation:
* changing `did` to be sometimes `did:web` broke how access-client depended on it
=> Revert "feat: access-api version route sets did=ucantoServerId and adds a signer prop"

packages/access-api/src/routes/version.js
Motivation:
* make it easy to discover the ucanto server principal
* unlike [reverted PR](https://github.com/web3-storage/w3protocol/pull/305), don't change `did` property
* because at least `@web3-storage/access` cli expects to be able to parse that value as a Verifier, which it can only do when the `did` is a `did:key`
=> feat: include ucanto server principal did as 'aud' key in /version endpoint

packages/access-api/src/bindings.d.ts, packages/access-api/src/config.js, packages/access-api/src/routes/version.js
...which is always the underlying did:key publicKey, even if signer.did() is a did:web
Motivation
* https://github.com/web3-storage/w3protocol/issues/316
* historically there has been a `did` property, which is (historically) always a `did:key` (so a public key)
* now we deal with non-key dids like `did:web`. So the did may not be identical to the public key (you have to resolve a `did:web` to determine its pubkeys)
* we should have a property that is explicitly only ever a public key (serialized as a `did:key` string)
* e.g. for code like this to rely on: https://github.com/web3-storage/w3protocol/blob/main/packages/access-client/src/cli/utils.js#L40 (which I think will break when version endpoint's `did` property is a `did:web`)
Rants
* try to avoid calling things 'did' when you mean …
=> feat(access-api): access-api version endpoint has publicKey property

.github/workflows/api-gateway.yml
Motivation:
* testing workflow for when this source branch is deleted after PR merge (it should call `wrangler delete`)
=> chore: remove unnecessary step from api-gateway workflow

packages/upload-client/README.md, packages/upload-client/src/car.js, packages/upload-client/src/index.js, packages/upload-client/src/sharding.js, packages/upload-client/src/types.ts, packages/upload-client/test/car.test.js, packages/upload-client/test/helpers/block.js, packages/upload-client/test/helpers/car.js, packages/upload-client/test/helpers/random.js, packages/upload-client/test/index.test.js, packages/upload-client/test/sharding.test.js
The PR adds an `uploadCAR` function to the client.
It differs from `Store.add` because it automatically shards the CAR file, calls `Store.add` for each shard and finally registers an upload (using `Upload.add`). This is very similar to `uploadFile` or `uploadDirectory` except it skips the UnixFS encoding step.
Once merged, I'll propogate this to the https://github.com/web3-storage/w3cli so that @lanzafame can upload BIG CARs and have them automatically sharded.
=> feat: add uploadCAR function

packages/access-api/src/service/upload-api-proxy.js
Motivation:
* attempt to fix according to this theory https://github.com/web3-storage/w3protocol/issues/359#issuecomment-1386434483
=> fix: upload-api-proxy default fetch binds to globalThis

package.json
I'm on the fence about this PR but figured I'd open it for review/discussion — feel free to close!
The README specifies "We use `pnpm` in this project" and node.js has some (experimental) support for actually capturing and using that metadata (see https://nodejs.org/api/corepack.html#configuring-a-package).
Notes:
* frankly the full implications here are unclear to me but it seems a relatively harmless to capture this programmatically rather than just in the README
* testing against node v18.12.1 with this in place, and after I `corepack enable` then `pnpm --version` reflects whatever version is currently in the package.json in some sort of `npx` style auto-install fashion
* it does not seem to be possible to specify a flexible version like ^7.24.3 or even a more generic pnpm@7 without …
=> chore: specify pnpm in packageManager for corepack

packages/access-api/readme.md, readme.md
I've added a few more tips/hints to get someone from a fresh checkout to accessing their own dev version of the API server. Should be no impact on the more public-facing (client library) documentation, just clarifying/extending the local environment setup notes.
=> docs: smooth out on-boarding for local API testing

packages/access-api/src/service/index.js
…that logs unexpected responses with status=530
Motivation:
* gather more info for [this error happening in production](https://github.com/web3-storage/w3protocol/issues/363#issuecomment-1396114241)
Plan
* gather info, then revert this PR
=> feat: access-api createStoreProxy uses patched fetch that will log any non-ok responses (to debug)

packages/access-api/src/ucanto/proxy.js, packages/access-api/test/helpers/upload-api.js, packages/access-api/test/ucanto-proxy.test.js
, which defaults to something that catches HTTPErrors and rewrites to a status=502 error result
Motivation:
* relates to: https://github.com/web3-storage/w3protocol/issues/363
* instead of that behavior of getting a `HandlerExecutionError` (due to internally having an uncaught `HTTPError`), after this PR we should
* not have the uncaught `HTTPError`, so no uncaught `HandlerExecutionError`
* the result will have `status=502` and `x-proxy-error` with information about the proxy invocation request that errored (which will help debug #363)
Limitations
* This inlcudes in `result['x-proxy-error']` any info from the underlying `@ucanto/transport/http` `HTTPError`, but unless/until we put more info on that error, we still won't have the raw response object and e.g. won't have response headers.
* …
=> feat: access-api proxy.js has configurable options.catchInvocationError, by default catches HTTPError -> error result w/ status=502

packages/access-api/src/service/index.js
because it will throw an [error](https://sentry.io/organizations/protocol-labs-it/issues/3885402347/?project=6536511&query=is%3Aunresolved&referrer=issue-stream) when accessed
`Failed to get the 'type' property on 'Response': the property is not implemented.`
=> fix: debug logging describeFetch does not access `response.type`

packages/access-api/src/service/upload-api-proxy.js
Motivation
* work around https://github.com/web3-storage/w3protocol/issues/363 by not using the domain name that cloudflare workers can't resolve. Instead bypass that dns rule and just request the aws http gateway domain
=> feat: upload-api-proxy production url is to aws http gateway instead of up.web3.storage

packages/capabilities/readme.md
This closes #369 by adding some examples of using the capability objects exposed by the capabilities package and explaining what some of the fancy type signatures are for.
=> chore: add examples & context to capabilities package readme

docusaurus.config.js, package.json, pnpm-lock.yaml
This adds a minimal [docusaurus](https://docusaurus.io) config file that allows us to use [docusaurus-plugin-typedoc](https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/docusaurus-plugin-typedoc) to generate markdown files that are compatible with docusaurus.
**Context**
As part of https://github.com/web3-storage/web3.storage/issues/2190, I want to render the typedoc outputs for all our "user facing" packages. The idea is that I would make a shallow clone of this repo when building the docs site and run `pnpm run docs:markdown` to generate the markdown files, then copy them into the content dir, along with the outputs of `w3up-client` and whatever other packages we end up putting in there.
The plugin really wants to be part of a docusaurus project, but it will run …
=> chore: add config to generate markdown API docs

packages/capabilities/package.json, packages/capabilities/src/access.js, packages/capabilities/src/index.js, packages/capabilities/src/types.ts, packages/capabilities/test/capabilities/access.test.js
=> feat(capabilities): implement access/authorize and ./update caps

packages/access-api/postmark/README.md, packages/access-api/postmark/welcome.html, packages/access-api/postmark/welcome.txt
This adds copies of the current Postmark `TemplateAlias: 'welcome'` content, shared by @travis via:
* https://filecoinproject.slack.com/archives/C04J6BGPULQ/p1673985987052709?thread_ts=1673648573.433349&cid=C04J6BGPULQ (html)
* https://filecoinproject.slack.com/archives/C04J6BGPULQ/p1673986008694189?thread_ts=1673648573.433349&cid=C04J6BGPULQ (text)
For the purposes of this PR please do **not** review the actual content! There are some known issues with the current plaintext template that will need to be addressed (xref https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1673986091876469 / #356) and some future enhancements being discussed. But those are examples of things that would be nice to have a commit history for going forward.
The goal of this change is simply to capture the …
=> chore: add current email templates to repo for reference/tracking

packages/access-api/src/service/index.js, packages/access-api/test/space-info.test.js, packages/access-client/src/errors.ts, packages/access-client/src/types.ts
Motivation:
* implement https://github.com/web3-storage/w3protocol/issues/382
* tl;dr `space/info` now has explicit failure type for case where the ucans are valid, but the space DID is not in the db. that way when upload-api invokes `space/info` as part of its `verifyInvocation` logic, it can distinguish between an invalid invocation and a not-found space id
Unblocks:
* this test passing https://github.com/gobengo/w3protocol-test/pull/1
* rest of https://github.com/web3-storage/w3infra/issues/134#user-content-implementation
=> feat: access-api handling store/info for space not in db returns failure with name

packages/access-api/migrations/0004_add_accounts_table.sql, packages/access-api/src/bindings.d.ts, packages/access-api/src/models/accounts.js, packages/access-api/src/models/spaces.js, packages/access-api/src/models/validations.js, packages/access-api/src/routes/validate-email.js, packages/access-api/src/service/access-authorize.js, packages/access-api/src/service/index.js, packages/access-api/src/utils/common.js, packages/access-api/src/utils/context.js, packages/access-api/src/utils/d1.js, packages/access-api/src/utils/did-mailto.js, packages/access-api/src/utils/html.js, packages/access-api/test/access-authorize.test.js, packages/access-client/package.json, packages/access-client/src/types.ts, packages/capabilities/src/access.js, packages/capabilities/src/index.js, pnpm-lock.yaml
closes #386
```mermaid
sequenceDiagram
autonumber
actor Alice
participant Web3
Alice->>+Web3: access/authorize
par Web3 responds to Alice
Web3->>Alice: Ok
and Web3 sends Alice email
Web3--)-Alice: ./update
end
Alice --) Web3: send DID (ws)
Web3 -->> Web3: Polls KV for DID
Alice --) Alice: Click email
Alice ->>+ Web3: ./update
Web3 -->> Web3: saves ./update
Note right of Web3: KV put [AliceDID, ./update, 5mins]
Web3 ->>-Alice: HTML with ./update
Note right of Web3: 5. finds Alice DID
Web3 --) Alice: sends ./update (ws from 4.)
```
=> feat: add support for access/authorize and update

packages/capabilities/package.json, packages/capabilities/src/access.js, packages/capabilities/test/capabilities/access.test.js
Motivation:
* https://github.com/web3-storage/w3protocol/issues/408
Unblocks:
* people importing a canonical CapabilityParser for `access/claim`
* adding advanced tests e.g. by [reverting this and finishing the TODOs](https://github.com/web3-storage/w3protocol/pull/409/commits/fd0b56ff7459d0178e3b9daa64a59bf1bcd9a463)
* these involve `can=./update` abilities, so may make most sense to add after https://github.com/web3-storage/w3protocol/pull/392 which defines tools for them
=> feat: define access/claim in @web3-storage/capabilities

packages/access-api/src/bindings.d.ts, packages/access-api/src/config.js, packages/access-api/src/service/upload-api-proxy.js, packages/access-api/src/utils/context.js, packages/access-api/test/helpers/context.js, packages/access-api/test/store-list.js, packages/access-api/wrangler.toml
Motivation:
* https://github.com/web3-storage/w3protocol/issues/406
* tl;dr remove some code/behavior that's not strictly needed and @hugomrdias asked me to remove
=> feat: rm upload-api-proxy ability to route to separate environment audiences

spec/capabilities.md
`store/list` and `upload/list` both accept paging parameters - document them.
=> chore: add documentation for paging caveats

packages/access-client/readme.md, packages/upload-client/README.md
This fixes the capability imports in the upload-client examples to close #326
I didn't see any more references to the old import paths, but lmk if I missed any.
I also changed the casing of `Agent` and `Space` in a few places; when I first wrote the access client readme I went a little nuts with the capitalization, but later decided it looked weird and stopped capitalizing them everywhere. So this just makes things consistent with the docs site, etc.
=> chore: small readme updates

packages/capabilities/package.json, packages/capabilities/src/access.js, packages/capabilities/test/capabilities/access.test.js
Motivation:
* https://github.com/web3-storage/w3protocol/issues/414
=> feat: add access/delegate capability parser exported from @web3-storage/capabilities

packages/access-api/postmark/welcome.txt
originally added as #403, moving here to make rebasing easier
this fixes #356 in the repo, but will need to be applied in Postmark before truly resolved (xref #402)
=> fix: align postmark/welcome.txt with .html version

packages/access-api/src/index.js, packages/access-api/src/routes/validate-email.js, packages/access-api/src/utils/html.js, packages/access-api/test/access-authorize.test.js, packages/access-api/test/space-recover.test.js
Originally proposed in #398, moved here to make rebasing simpler and to fix tests.
Original PR message from @natevw:
The email validation approval process is now split into two stages: a GET request with no side effects except to load a page, that then auto-submits a POST request to actually continue the flow.
This fixes the API so as to follow [proper HTTP semantics](https://github.com/web3-storage/w3protocol/issues/333#issuecomment-1380925535):
> The purpose of distinguishing between safe [i.e. like GET] and unsafe [like PUT/POST] methods is to allow automated retrieval processes (spiders) and cache performance optimization (pre-fetching) to work without fear of causing harm. In addition, it allows a user agent to apply appropriate constraints on the automated use of unsafe methods when …
=> fix: avoid email delegation via GET request

packages/capabilities/src/store.js, packages/capabilities/src/upload.js, packages/upload-client/src/store.js, packages/upload-client/src/types.ts, packages/upload-client/src/upload.js, spec/capabilities.md
Per https://github.com/web3-storage/w3ui/issues/143 we'd like to give clients a way to get the previous page of results rather than the next page.
This change introduces a `pre` caveat which, when set to true, will return the page of results preceding `cursor`.
I considered calling this `reverse` or `rev` but I think that implies that results will be returned sorted in reverse, which is not the intent.
=> feat: add `pre` caveat to `store/list` and `upload/list`

spec/capabilities.md
it looks like I fumbled a merge somewhere and we have duplicate caveat tables under `upload/list` - fix that
plus, fix spelling error - s/preceeding/preceding/
=> chore: fix merge gone bad

packages/access-client/src/agent.js
This fixes https://github.com/web3-storage/w3protocol/issues/344 and makes it possible to connect to staging services with w3ui.
This PR obsoletes https://github.com/web3-storage/w3protocol/pull/404 per @alanshaw's suggestion in https://github.com/web3-storage/w3protocol/pull/404#issuecomment-1437391750 based on reasoning in https://github.com/web3-storage/ucanto/pull/214#issuecomment-1437271520 which points out that some sort of conditional or casting is probably unavoidable here.
My solution casts the channel to have an optional `url` field and looks in that field for a URL before falling back to the default `HOST`.
Have tested this locally with w3ui and verified it makes it possible to connect to staging services from w3ui - huzzah!
=> fix: look for URL in channel before falling back to default

packages/upload-client/src/types.ts
Per the reasoning and change in https://github.com/web3-storage/w3infra/pull/148
=> feat!: rename startCursor and endCursor to before and after

packages/access-api/package.json, packages/access-api/src/models/delegations.js, packages/access-api/src/service/access-claim.js, packages/access-api/src/service/delegations.js, packages/access-api/src/types/delegations.ts, packages/access-api/test/access-delegate.test.js, packages/access-api/test/delegations-storage.test.js, pnpm-lock.yaml
Note:
* this PR targets https://github.com/web3-storage/w3protocol/tree/1675728220-handle-access-delegate
Motivation:
* this patch has things that are more related to #394 . They don't need to be a part of #427, which is motivated by #425. I don't mind putting them alltogether, but I'm holding these out while iterating on #427 based on review
=> feat: `access/claim` only claims delegations with the correct audience

packages/access-api/src/service/index.js, packages/access-api/test/access-claim.test.js, packages/access-api/test/access-delegate.test.js, packages/access-api/test/helpers/ucanto-test-utils.js, packages/access-client/src/types.ts
Motivation:
* https://github.com/web3-storage/w3protocol/issues/455
* this will definitely resolve this error https://github.com/gobengo/w3protocol-test/actions/runs/4267476381/jobs/7429121484#step:6:66
=> feat: access-api serves access/claim invocations

packages/access-api/src/models/delegations.js, packages/access-api/src/routes/validate-email.js, packages/access-api/src/service/access-claim.js, packages/access-api/src/service/voucher-claim.js, packages/access-api/src/types/delegations.ts, packages/access-api/test/access-authorize.test.js, packages/access-api/test/access-delegate.test.js, packages/access-api/test/voucher-claim.test.js
Motivation:
* #455 
* This implements the second delegation described in https://github.com/web3-storage/w3protocol/issues/457
* make this test pass once we deploy this to staging https://github.com/gobengo/w3protocol-test/pull/6
Test Case:
* https://github.com/gobengo/w3protocol-test/pull/6/files#diff-698e92d7467a4a470689d4cb120272c6cac28864d4960ac12a3720ab7c35a15cR364
=> feat: access/authorize confirmation email click results in a delegation back to the issuer did:key so that access/claim works

.env.tpl, packages/access-api/src/bindings.d.ts, packages/access-api/src/service/access-authorize.js, packages/access-api/src/utils/context.js, packages/access-api/src/utils/email.js, packages/access-api/test/access-authorize.test.js, packages/access-api/test/helpers/context.js, packages/access-api/test/store-list.js, packages/access-api/test/ucan.test.js, packages/access-api/test/upload-api-proxy.test.js, packages/access-client/src/types.ts, packages/capabilities/src/types.ts
Makes `email` thing injectable for tests as opposed to overloading the response type for testing purposes.
=> fix: allow injecting email

packages/access-api/src/routes/validate-email.js, packages/access-api/src/service/access-authorize.js, packages/access-api/src/service/index.js, packages/access-api/src/utils/context.js, packages/access-api/test/access-authorize.test.js, packages/access-api/test/helpers/ucanto-test-utils.js, packages/capabilities/src/access.js, packages/capabilities/src/types.ts, packages/capabilities/test/capabilities/access.test.js
This pr cleans up bunch of mess in the access/authorize code path and starts including proof chains in the delegated authorization so agents can actually utilize delegations.
=> feat: includes proofs chains in the delegated authorization chain

packages/access-api/migrations/0005_drop_delegations_audience_to_accounts_did_fk.sql
Note:
* this is just for consideration because @Gozala and I are both curious whether cloudflare migrations will allow the rename. It would be good to know.
* But i actually think it would probably be best to use https://github.com/web3-storage/w3protocol/pull/469 over time
Motivation:
* try out something @Gozala and I came up with for https://github.com/web3-storage/w3protocol/issues/464
=> fix: adjust migration 0005 to not do a drop table and instead rename delegations -> delegations_old and create a new delegations

packages/access-api/migrations/0005_drop_delegations_audience_to_accounts_did_fk.sql, packages/access-api/src/models/accounts.js, packages/access-api/src/models/delegations.js
Motivation:
* similar to https://github.com/web3-storage/w3protocol/pull/468
I think this is the one we should actually do, even though it is a little ugly to call the table `delegations_v2`.
If d1 can't do DROP TABLE, then I think the safest thing to do is to avoid it and always only ever create new ones. We can migrate to new tables and update the table name access-api uses in the same commit/pr.
=> fix: adjust migration 0005 to keep delegations table but create new used delegations_v2

packages/access-api/src/models/delegations.js, packages/access-api/test/delegations-storage.test.js
Motivation:
* aid in debugging #471 
* hope this
* confirms that this error is coming from `DbDelegationsStorage#find` (I see '.find' in the hard-to-read sentry stack trace)
* gives insight into what the db row is like (esp `row.bytes`) that can't be parsed
=> fix: DbDelegationsStorage#find throws UnexpectedDelegation w/ { row } if failed bytesToDelegations

packages/access-api/src/models/delegations.js, packages/access-api/src/service/voucher-redeem.js, packages/access-api/src/utils/context.js, packages/access-api/src/utils/d1.js, packages/access-api/test/helpers/context.js
This is the error I get from staging atm (on `access/claim`)
```
claimResult {
name: 'HandlerExecutionError',
cause: {
row: {
cid: 'bafyreihqswtsrxvsp2pqf5a2jjiyb6zks3hynbfkhga7odwbat4ptxrf5e',
bytes: [Array],
issuer: 'did:mailto:dag.house:bengo',
audience: 'did:key:z6MkkUymFxGqXWRqFNiaU4jCa2efexfDCNADqD7sQK3RbU2j',
expiration: null,
updated_at: '2023-03-03T16:41:54.999Z',
inserted_at: '2023-03-03T16:41:54.999Z'
},
name: 'UnexpectedDelegation',
stack: 'UnexpectedDelegation: failed to create delegation from row\n' +
```
Notably `bytes` is `Array` here.
Locally and in node.js, I think miniflare gives back a `Buffer` and (in nodejs) [this catches it](https://github.com/web3-storage/w3protocol/blob/a6dafcb0c44b20fa87bbe81d7a982fb13387084e/packages/access-api/src/utils/d1.js#L77). But on …
=> fix: delegations model tries to handle if row.bytes is Array not Buffer (e.g. cloudflare)

.github/workflows/upload-api.yml, packages/upload-api/package.json, packages/upload-api/test/car-store-bucket.js, packages/upload-api/test/util.js, pnpm-lock.yaml
Running tests in w3infra failed because `Blob` is not in node16. Change ci to use node 16 for upload-api to avoid this problem.
=> fix: switch upload-api to node16

packages/access-api/src/models/spaces.js, packages/access-api/src/service/index.js, packages/access-api/test/provider-add.test.js, packages/access-client/src/types.ts
Motivation:
* #497 
* @Gozala and I talked about doing this minimally just to make sure that when w3infra calls this as part of handling `store/add` that it will work.
=> feat: space/info will not error for spaces that have had storage provider added via provider/add

packages/access-api/src/routes/validate-email.js, packages/access-api/src/utils/html.js, packages/access-api/test/validate-email.test.js
Motivation:
* https://github.com/web3-storage/w3protocol/issues/503
=> feat: if POST /validate-email?mode=authorize catches error w/ too big qr code

packages/access-api/src/models/provisions.js, packages/access-api/src/service/provider-add.js, packages/access-api/src/types/provisions.ts, packages/access-api/test/provisions.test.js
Motivation:
* https://github.com/web3-storage/w3protocol/issues/482
After 2023-03-09 review with @Gozala :
fields. it should result in error
* it wasn't really possible to do that on conflict logic as far as I could tell, at least through our `kysely` orm
* kysely doesn't expose methods for all the [`on conflict` clauses that sqlite should support](https://www.sqlite.org/lang_conflict.html)
* I pursued something like [this using CTE](https://stackoverflow.com/a/49601238), only to find out [sqlite doesn't support `insert` in cte](https://sqlite.org/forum/forumpost/b44ca81f043bed9f)
=> fix: DbProvisionsStorage putMany doesnt error on cid col conflict

packages/access-api/src/models/provisions.js, packages/access-api/src/service/index.js, packages/access-api/src/service/provider-add.js, packages/access-api/src/types/provisions.ts, packages/access-api/src/utils/context.js, packages/access-api/test/helpers/types.ts, packages/access-api/test/provider-add.test.js, packages/access-api/test/provisions.test.js, packages/capabilities/src/provider.js, packages/capabilities/test/capabilities/provider.test.js
* previously the only allowed storage provider on `provider/add` was a `w3up-alpha` one. I never planned on it being a ucan issuer
* this changes the storage provider id to be the same as the running service, e.g. `did:web:web3.storage` in prod.
* This makes the `Provision` type generic on `ServiceId`
=> feat: provision provider type is now the DID of the w3s service

packages/access-api/src/types/ucanto.ts, packages/access-api/test/access-client-agent.test.js, packages/access-api/test/access-delegate.test.js, packages/access-api/test/helpers/types.ts, packages/access-api/test/helpers/ucanto-test-utils.js, packages/access-api/test/provider-add.test.js
Motivation:
* there weren't any tests that test access-api + access-client agent, so this adds a stub for one
* it includes a lot of type adjustments that should make it easier to write more tests in followup
* specifically it removed some old types I had tried to make when testing access delegate. I added a new `ServiceInvoke` type that is better than the ones I had made before. This is useful for making an 'invoke' function that will handle a subset of the caps available on `Service` but expect the same success/fail types as Service
=> feat: add access-api + access-client agent test and improve types

packages/upload-client/package.json, packages/upload-client/src/unixfs.js, packages/upload-client/test/index.test.js, packages/upload-client/test/sharding.test.js, pnpm-lock.yaml
This PR updates the UnixFS configuration to bring it in line with the [configuration used in our existing client](https://github.com/web3-storage/web3.storage/blob/main/packages/client/src/lib.js#L153-L159).
Block size is 1MB and max children per node is 1024.
=> feat: use bigger block sizes and increase max children

packages/upload-client/package.json, packages/upload-client/src/unixfs.js, packages/upload-client/test/index.test.js, packages/upload-client/test/sharding.test.js, packages/upload-client/test/unixfs.test.js, pnpm-lock.yaml
Updates `@ipld/unixfs` to pull in the HAMT sharded directories support and use it in the `upload-client`. If the directory contains more than 1,000 entries it will be sharded.
=> feat: add HAMT sharded directories support

packages/access-client/src/agent-data.js, packages/access-client/src/agent.js, packages/access-client/src/types.ts, packages/access-client/src/utils/did-mailto.js
Motivation:
* https://github.com/web3-storage/w3protocol/pull/433/files#r1137631263
=> fix: rm mention of 'sessionPrincipal' from agent and agent-data

packages/access-api/test/access-client-agent.test.js, packages/access-client/src/agent.js
Motivation:
* move towards unbundling `authorize()` into e.g. `requestAuthorization()` + (future) `wait.....`
=> feat: Agent#requestAuthorization

packages/access-client/src/agent-use-cases.js, packages/access-client/src/agent.js
some hacky logic to enable the "claim spaces on second device" flow - @bengo and I are planning on refactoring this whole API to pull spaces out of the agent but want to get it working with the current API first
=> feat: store spaces after claiming delegations

packages/access-api/test/access-client-agent.test.js, packages/access-client/src/agent-data.js, packages/access-client/src/agent-use-cases.js, packages/access-client/src/agent.js, packages/access-client/src/utils/ws.js
TIL:
* the websocket definitely doesn't really work in access-api tests, because access-ws is an entirely different cf worker! it's not running in those access-api tests
* so 100% of the time the websocket immediately terminates with ECONNREFUSED, but afaict that error isn't really bubbled up when Agent calls `await ws.open`. This still doesn't bubble up that error, but does allow for that open to be abortable
* and then authorize() races that websocket and polling access claim. If access/claim polling wins, it aborts the websocket, and everything kinda maybe works
End result
* this re-enables a test against Agent#authorize, which passes due to the polling  on access/claim
* in the wild maybe the websocket will win the race sometimes
(so it can be used in tests)
=> fix: Agent#authorize races websocket and polling access/claim 

packages/access-api/test/access-client-agent.test.js, packages/access-client/src/agent-use-cases.js, packages/access-client/src/agent.js
Motivation:
* avoid adding new public method to Agent that can be a function that operates on the existing public api
=> fix: access-client authorize and waitForDelegation use cases

.github/release-please-config.json
per documentation here: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
=> chore: use prerelease versions for access client for now

.github/release-please-config.json
Per instructions and examples here:
https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
Set package numbers manually for now. Release Please is currently very confused because we set a prerelease version number using a commit and now it wants to release everything with that version number. This should fix that.
After we release these packages we should be able to delete these and it will go back to guessing based on conventional commits.
=> chore: set package versions manually for now

packages/access-api/src/bindings.d.ts, packages/access-api/src/config.js, packages/access-api/src/utils/context.js, packages/access-api/test/helpers/context.js, packages/access-api/wrangler.toml
Motivation:
* https://github.com/web3-storage/w3protocol/pull/578#discussion_r1145521662
* https://github.com/web3-storage/w3protocol/pull/578#discussion_r1145504659
=> chore: rename ACCESS_API_R2 binding to DELEGATIONS, and configure wranger.toml to use env-specific buckets

packages/access-api/src/utils/context.js
Motivation:
* this is no longer useful. it helped us catch another bug. https://github.com/web3-storage/w3protocol/pull/629
* now we may want to remove these configs in an env, so we don't want it to throw in that case
=> fix: access-api utils/context no longer throws in staging and prod if UCAN configs are falsy

packages/access-api/test/access-client-agent.test.js, packages/access-client/src/agent-use-cases.js
Motivation:
* https://github.com/web3-storage/w3protocol/issues/633
Note:
* this was an unintentional addition to our package exports and not an intentional addition to our public API, so this PR conventional commit message is not marked as a breaking api change
* I notified the only person I expect to have relied on it https://github.com/web3-storage/w3protocol/pull/602#issuecomment-1482000952
=> fix: @web3-storage/access/agent no longer exports authorizeWithPollClaim

packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/upload-client/src/unixfs.js, packages/upload-client/test/unixfs.test.js
This PR adds a callback that is called when a directory entry has been encoded as a DAG. The callback recieves a parameter with the following data:
```ts
interface DirectoryEntryLink {
/** Content Identifier */
cid: Link
/** Name (full path) */
name: string
/** Cumulative number of bytes in the target DAG, that is number of bytes in the block and all the blocks it links to. */
dagByteLength: number
}
```
You'd use it like:
```js
client.uploadDirectory(conf, files, { onDirectoryEntryLink: l => console.log(l) })
```
This allows users to easily discover the CID and (DAG) size of all the files and directories within a directory as well as the root directory.
Specifically, thirdweb are uploading files separately and want to later tie them all together in a directory. For that they need to know …
=> feat: callback for directory entry link

.github/release-please-config.json
Motivation:
* instruct release-please what the w3up-client version number should be so it doesn't try 11.0.x
=> chore: update release-please-config.json so w3up-client has release-as 5.2.0

packages/w3up-client/src/client.js, packages/w3up-client/src/types.ts
Exposes the `onDirectoryEntryLink` option from https://github.com/web3-storage/w3protocol/pull/657 in `w3up-client`.
=> feat: expose `onDirectoryEntryLink` option

.github/release-please-config.json
Motivation:
* we don't need this now that 5.2.0 was released
* planned followup to https://github.com/web3-storage/w3protocol/pull/662 (which was required to get release-please-action to detect the right next release number in a new repo)
=> chore: remove release-as for w3up-client in release-please-config.json

packages/w3up-client/.github/actions/test/action.yml, packages/w3up-client/package.json, packages/w3up-client/src/base.js, packages/w3up-client/src/capability/access.js, packages/w3up-client/src/capability/space.js, packages/w3up-client/src/capability/store.js, packages/w3up-client/src/capability/upload.js, packages/w3up-client/src/client.js, packages/w3up-client/src/delegation.js, packages/w3up-client/src/index.js, packages/w3up-client/src/index.node.js, packages/w3up-client/src/service.js, packages/w3up-client/src/space.js, packages/w3up-client/src/types.ts, packages/w3up-client/test/capability/access.test.js, packages/w3up-client/test/capability/space.test.js, packages/w3up-client/test/capability/store.test.js, packages/w3up-client/test/capability/upload.test.js, packages/w3up-client/test/client.test.js, packages/w3up-client/test/helpers/bucket-server.js, packages/w3up-client/test/helpers/car.js, packages/w3up-client/test/helpers/mocks.js, packages/w3up-client/test/helpers/random.js, packages/w3up-client/test/helpers/shims.js, packages/w3up-client/tsconfig.json, pnpm-lock.yaml, tsconfig.json
make it consistent with other packages in this monorepo so that the top level prettier format command doesn't make unexpected changes when trying to format other packages
=> chore: update w3up-client linter

packages/w3up-client/src/index.node.js, packages/w3up-client/src/types.ts, packages/w3up-client/test/index.node.test.js
This is https://github.com/web3-storage/w3up-client/pull/74 ported here.
---
This PR allows passing your own principal to the client `create` factory function instead of loading one from a pre-existing store. The caveat is that if you pass your own and the store is not empty then it needs to match the principal that was loaded from the store (otherwise any saved delegations will be unusable).
This makes https://gist.github.com/alanshaw/e949abfcf6728f590ac9fa083dba5648#on-the-server a little easier, you won't need to install `@web3-storage/access` or deal with the `AgentData` class.
Currently:
```js
import * as Signer from '@ucanto/principal/ed25519'
import { AgentData } from '@web3-storage/access/agent'
import { Client } from '@web3-storage/w3up-client'
const principal = …
```
=> feat: bring your own principal

packages/w3up-client/package.json, packages/w3up-client/src/client.js, packages/w3up-client/src/space.js, packages/w3up-client/test/capability/access.test.js, packages/w3up-client/test/capability/space.test.js, packages/w3up-client/test/capability/store.test.js, packages/w3up-client/test/capability/upload.test.js, packages/w3up-client/test/client.test.js, packages/w3up-client/test/helpers/mocks.js, packages/w3up-client/tsconfig.json, pnpm-lock.yaml
Non-goal
* changing src code
* avoidance of all ts-ignore in these newly included files (that can come as iteration)
Context:
* https://github.com/web3-storage/w3protocol/issues/668#issuecomment-1485989307
=> test: w3up-client tsconfig.json now includes "./test" so its tests have some type checking

packages/access-client/package.json, packages/access-client/src/agent.js, packages/access-client/test/agent.test.js
Previously `this.proofs(caps)` was returning `[]` when you request capabilities the agent is not authorized to use, the call to `delegate` would succeed and you get a useless delegation because there are no proofs.
=> fix: verify proofs exist for requested delegation capabilities

packages/access-client/src/agent.js, packages/access-client/test/agent.test.js
Removes the restriction that importing a space should have `*` capability.
Alternative to https://github.com/web3-storage/w3protocol/pull/671
=> feat: allow importing a space with restricted abilities

packages/access-api/src/utils/did-mailto.js, packages/access-api/test/access-client-agent.test.js
… right, causing access/authorize not to send emails for email addresses with '+'
Motivation:
* https://github.com/web3-storage/w3cli/issues/73
=> fix: bug where did:mailto with pct-encoded email parts was not decoded correctly

packages/access-api/package.json, packages/access-api/src/utils/context.js, pnpm-lock.yaml
Motivation:
* #623 
* test theory that things will work if we upgrade to toucan-js@3, which is a rewrite that sends source maps in a new way
=> fix: upgrade toucan-js and @web3-storage/worker-utils

packages/access-api/package.json, packages/access-api/src/utils/context.js, pnpm-lock.yaml
Motivation:
* https://github.com/web3-storage/w3up/issues/623#issuecomment-1499833258
* this was suggested by toucan-js author as no longer being needed in 3.0.0.
=> fix: toucan-js in access-api does not use RewriteFrame integration

packages/access-api/scripts/cli.js
Motivation:
* https://github.com/web3-storage/w3up/issues/623#issuecomment-1499808790
=> fix: access-api cli.js build does sourcemap=external instead of true

packages/access-api/src/index.js
=> fix: change access-api src/index.js 'export default' to be an immediately-defined object in hopes stack traces will work better

packages/access-api/src/config.js
The service is not fully operational without this environment variable - it's unable to send emails to authorize users and so is unusable for anyone who does not already have an existing auth session.
I think it was a mistake to remove this - if it was intentional, then we also need to update the reference to `vars.POSTMARK_TOKEN` below to refer to `env.POSTMARK_TOKEN`.
=> fix: add POSTMARK_TOKEN back to list of required env

packages/access-client/src/agent-use-cases.js, packages/access-client/test/agent-use-cases.test.js
My previous implementation (https://github.com/web3-storage/w3up/pull/756) relied on canceling a timeout to stop the polling process. This had a number of edge cases, including one where the signal was aborted before first round of polling happened, which is quite common since we do some network calls before we even get to this code.
Stop worrying about canceling the timeout since we'll just stop polling whenever we execute `poll` in this new implementation - generally this relies on a piece of "persistent" state (in the sense that `signal.aborted` will continue to be true) rather than the assumption that the correct timeout will get canceled, so is quite a bit more robust.
=> fix: account for edge cases in polling abort

packages/upload-client/README.md, packages/w3up-client/README.md
`uploadCAR` actually returns the root CID, which is either the root CID in the CAR header, the passed `rootCID` option value or the CID of the last block in the CAR.
=> fix: docs for `uploadCAR` return value

packages/upload-api/src/access/confirm.js, packages/upload-api/src/access/delegate.js, packages/upload-api/src/types/delegations.ts, packages/upload-api/test/delegations-storage-tests.js, packages/upload-api/test/delegations-storage.js
we'd like to stop storing copies of delegations separately, and to do that we need to pass the CID of the invocation where the delegations do live so that we can grab it and pull delegations out of it when they are requested. This interface change enables this change, which is implemented in w3infra in https://github.com/web3-storage/w3infra/pull/201
=> feat: enable reuse of stored invocations for delegations storage

packages/upload-api/src/access/confirm.js, packages/upload-api/src/access/delegate.js, packages/upload-api/src/types/delegations.ts, packages/upload-api/test/delegations-storage-tests.js, packages/upload-api/test/delegations-storage.js
Move the `cause` parameter of `putMany` into an options hash and make clear that it is an optional parameter intended to allow some storage implementations to not store delegations themselves but instead rely on CID-identified UCAN invocations that they already have access to.
=> feat: tweak `DelegationsStorage#putMany` to make `cause` optional

packages/upload-api/src/types/delegations.ts
it's possible for this to fail, so types should reflect that
=> feat: add failure type to DelegationsStorage#putMany return

packages/aggregate-api/package.json, packages/aggregate-api/src/aggregate/get.js, packages/aggregate-api/src/aggregate/offer.js, packages/aggregate-api/src/offer/arrange.js, packages/aggregate-api/src/types.ts, packages/aggregate-api/test/aggregate.js, packages/aggregate-api/test/context/aggregate-store.js, packages/aggregate-api/test/context/offer-store.js, packages/aggregate-api/test/utils.js, packages/aggregate-client/README.md, packages/aggregate-client/package.json, packages/aggregate-client/src/aggregate.js, packages/aggregate-client/src/types.ts, packages/aggregate-client/test/aggregate.test.js, packages/aggregate-client/test/helpers/car.js, packages/aggregate-client/test/helpers/random.js, packages/capabilities/package.json, packages/capabilities/src/aggregate.js, packages/capabilities/src/offer.js, pnpm-lock.yaml
Updates client and api based on https://github.com/web3-storage/specs/commit/63846e529a77d200af4a4a8bdab4c4ac7320c107
It also starts relying on the https://github.com/web3-storage/data-segment/ lib for the tests by generating commP of randomly generated CARs. In next iteration, tests should also include commP of commPs builder (needs https://github.com/web3-storage/data-segment/pull/8)
Client API for submitting offer was changed to receive piece instead of computing it. Main reason for this is that there is a need to build it outside while keeping track of sizes. It could also happen here and explode if not, even though this is an aggregate offer call and not really the builder. So I would love feedback on API surface preferences. This will not be used by end users as will be abstracted …
=> fix!: update aggregate spec in client and api

.github/workflows/access-client.yml, .github/workflows/aggregate-client.yml, .github/workflows/upload-client.yml, .github/workflows/w3up-client.yml, packages/upload-client/src/car.js
Support Node.js 20 in the clients.
Adds a temporary fix for Node.js 20 as `blob.stream()` is currently broken: https://github.com/nodejs/node/issues/48916
Also adds matrix config to CI workflows so that tests are run in both node 18 & 20.
=> fix: support for Node.js 20

packages/upload-api/package.json, packages/upload-api/test/access-authorize.js, packages/upload-api/test/store.js, packages/upload-api/test/upload.js
mocha's globbing behavior is... quirky. tests currently broken, working to fix.
=> fix: re-enable upload-api tests

packages/upload-api/src/space.js, packages/upload-api/src/types.ts, packages/upload-api/src/types/provisions.ts, packages/upload-api/test/provisions-storage.js, packages/upload-api/test/space-info.spec.js
I believe we currently don't have any way for an agent to figure out which providers a space is registered to - add a list of providers to `space/info` to enable this in the CLI and w3console
=> feat: add providers to space/info

packages/capabilities/src/types.ts, packages/upload-api/src/customer/get.js, packages/upload-api/src/types/provisions.ts, packages/upload-api/test/provisions-storage-tests.js, packages/upload-api/test/provisions-storage.js
this is needed by w3admin to be able to navigate from a customer to their subscriptions (ie, to see the spaces they've registered)
=> feat: add subscriptions to CustomerGetSuccess

packages/access-client/src/agent.js, packages/access-client/src/types.ts, packages/upload-api/test/access-client-agent.js
Right now we hardcode the Service type of an Agent to an old version of the access service types. This makes it possible to specify an arbitrary Service in the types, which should result in better typing behavior in clients.
=> feat: make agent Service generic

packages/capabilities/src/filecoin.js, packages/capabilities/src/index.js, packages/capabilities/src/types.ts, packages/filecoin-api/src/aggregator.js, packages/filecoin-api/src/dealer.js, packages/filecoin-api/src/storefront.js, packages/filecoin-api/src/types.ts, packages/filecoin-api/test/services/aggregator.js, packages/filecoin-api/test/services/dealer.js, packages/filecoin-api/test/services/storefront.js, packages/filecoin-client/src/aggregator.js, packages/filecoin-client/src/dealer.js, packages/filecoin-client/src/storefront.js, packages/filecoin-client/src/types.ts, packages/filecoin-client/test/aggregator.test.js, packages/filecoin-client/test/dealer.test.js, packages/filecoin-client/test/helpers/mocks.js, packages/filecoin-client/test/storefront.test.js
Per https://github.com/web3-storage/specs/pull/73
Closes #855
=> fix: w3filecoin spec separate capabilities to queue and enqueue

packages/upload-api/test/provisions-storage-tests.js, packages/upload-api/test/provisions-storage.js
this was not tested previously, which lead to staging failures in w3infra
=> fix: add a test that exercises ProvisionsStorage#getConsumer

packages/w3up-client/src/client.js, packages/w3up-client/test/client.test.js
These classes were not exported and so typescript was unable to determine the type.
=> fix: types for capability specific clients

packages/upload-api/src/store/add.js, packages/upload-api/test/store.js
`store/add` enforcing max single put size in context of w3filecoin https://github.com/web3-storage/w3up/issues/827
At this moment, we only fail to provide the presigned URL for upload if size is bigger, but we perform our DB insertions. storeTable insert, and more recently the allocation
- The reasoning for this is described in code: `checking this last, as larger CAR may already exist in bucket from pinning service fetch. we only want to prevent this here so we don't give the user a PUT url they can't use.`
- That makes sense to me from billing perspective. However, we will allocate way more bytes to the space than realistically happens, as well as show this in space store list. 
- Regarding Pinning Service, we should consider chunking into smaller CARs if that is realistic. Perhaps when …
=> fix: store add should validate size right away

packages/upload-client/README.md
making this a "fix" to bump the `upload-client` version and hopefully unstick the `upload-api` release process: https://github.com/web3-storage/w3up/actions/runs/6425748870/job/17449345888
=> fix: a couple URLs in the README

packages/upload-api/README.md
Doing this primarily to bump versions since the last release failed:
https://github.com/web3-storage/w3up/actions/runs/6425748870/job/17449345888
=> feat: Add basic README to upload-api

packages/capabilities/src/console.js, packages/capabilities/src/index.js, packages/capabilities/src/types.ts, packages/capabilities/src/ucan.js, packages/capabilities/test/capabilities/ucan.test.js, packages/upload-api/src/lib.js, packages/upload-api/src/types.ts, packages/upload-api/src/types/revocations.ts, packages/upload-api/src/ucan.js, packages/upload-api/src/ucan/revoke.js, packages/upload-api/src/utils/revocation.js, packages/upload-api/test/handlers/ucan.js, packages/upload-api/test/handlers/ucan.spec.js, packages/upload-api/test/helpers/context.js, packages/upload-api/test/lib.js, packages/upload-api/test/storage/revocations-storage-tests.js, packages/upload-api/test/storage/revocations-storage.js
Implements `ucan/revoke` capability and a ucanto server hook that performs the revocation checks.
I ended up changing revocations store interface to avoid serializing / deserializing UCN CIDs and to layout data in a way that it's would be more efficient to perform necessary lookups.
☹️ I'm not super happy about the way we have to interface with ucanto hook and probably it would make sense to change hook API so it's more like `query` on the revocations store. If we do that we would be able to uplift logic from `utils/revocation.js` into ucanto and simplify things here. That said I it's probably better to land thing here first and do the uplifting if we'll have time to do so.
=> feat: revocation handler

packages/upload-client/src/store.js
Is misleading to users - looks like things have failed when they are being retried automatically.
=> fix: do not log warning on failed retry

package.json, pnpm-lock.yaml, tsconfig.json
upgrade typedoc to be happy with the version of tsc we use, and to drop the ref to the missing css.
You can now run typedoc in the root of project again (as happens in CI)
```sh
❯ ./node_modules/.bin/typedoc
[info] Converting project at ./packages/access-client
[warning] No entry points were provided, this is likely a misconfiguration.
[info] Converting project at ./packages/capabilities
[info] Converting project at ./packages/upload-client
[info] Converting project at ./packages/filecoin-client
[info] Converting project at ./packages/w3up-client
[info] Merging converted projects
[info] Documentation generated at ./docs
```
fixes: https://github.com/web3-storage/w3up/issues/987
License: MIT
=> chore: fix typedoc generation

packages/access-client/src/agent-use-cases.js
this should get us through the next major round of product features, and adds a `w3up` namespace that we can use (or at least alias into) for future capabilities
=> feat: add more capabilities to the set we request on authorize

packages/filecoin-api/package.json, packages/filecoin-api/src/aggregator/api.ts, packages/filecoin-api/src/deal-tracker/api.ts, packages/filecoin-api/src/storefront/api.ts
Adds more exports of types to ease usage
=> chore: export more types to filecoin api

packages/upload-api/test/handlers/upload.js, packages/upload-api/test/storage/provisions-storage.js
this just updates the test `ProvisionsStorage` to behave the way the production `ProvisionsStorage` does as of https://github.com/web3-storage/w3infra/pull/246
=> feat: allow customers to create more than one space

packages/access-client/package.json, packages/filecoin-client/package.json, packages/upload-client/package.json
Motivation:
* https://github.com/web3-storage/w3up/pull/1004/files#r1372070039
=> fix: package.json files excludes 'src' and includes .js and .js.map in dist for packages that now export their module from dist 

.github/workflows/filecoin-client.yml, packages/filecoin-client/package.json
Motivation:
* https://github.com/web3-storage/w3up/issues/982
* I was testing the filecoin-client 2.0.1 release I did against attw and noticed it actually still fails for a tiny reason. https://arethetypeswrong.github.io/?p=%40web3-storage%2Ffilecoin-client%402.0.1
Change
* now CI for filecoin-client will use attw to prevent releases like this that dont pass attw check
* also update package.json to resolve the attw update for filecoin-client
=> ci: filecoin-client github workflow runs arethetypesworking tooling, passes due to removal of chain-tracker export

packages/filecoin-api/test/events/aggregator.js
Sadly we cannot test queue with groups, so we need to take expectations out and a few casts given BigInt does not play nicely with encodings
=> fix: aggregator event tests

.github/workflows/upload-api.yml, packages/filecoin-api/test/context/queue-implementations.js, packages/filecoin-api/test/context/service.js, packages/filecoin-api/test/storefront.spec.js, packages/upload-api/package.json, packages/upload-api/src/lib.js, packages/upload-api/src/types.ts, packages/upload-api/test/helpers/context.js, pnpm-lock.yaml
Adds `filecoin/*` to the `upload-api`, so that web3.storage implements storefront capabilities
This will enable us to integrate the new API with w3infra, so that clients can execute `filecoin/offer` to web3.storage.
=> feat!: add storefront filecoin api to upload api

packages/access-client/package.json, packages/access-client/src/agent-data.js, packages/access-client/src/agent-use-cases.js, packages/access-client/src/agent.js, packages/access-client/test/agent-data.test.js, packages/access-client/test/agent.test.js, packages/upload-api/src/access/confirm.js
Motivation:
* fix w3cli bug I witnessed in my local setup https://github.com/web3-storage/w3cli/issues/113
Context
* Why does this fix it?
* previously, it was possible for calls to `Agent#registerSpace` to fail due to invalid proofs, even if the underlying AgentData had the right proof. This was because `registerSpace` ends up calling `invokeAndExecute(Provider.add)`, which calls `invoke` to build the invocation, which calls `proofs` to get the proofs for the invocation. And `proofs` could fail to include a sessionProof that was appropriate for the invocation audience of the invocation built by `Agent#invoke`. Now, `Agent#proofs` returns all the sessionProofs that might be relevant.
* explanation of underlying cause of that w3cli issue 113 …
=> feat: access agent proofs method would fail to return some session proofs

packages/filecoin-api/src/aggregator/api.ts, packages/filecoin-api/src/aggregator/buffer-reducing.js, packages/filecoin-api/src/aggregator/events.js, packages/filecoin-api/src/aggregator/service.js, packages/filecoin-api/test/events/aggregator.js, packages/filecoin-api/test/services/aggregator.js
because not pieces cid block being used but buffer block, which was meaning a different CID being computed for invocation and receipt, as seen in:
- https://github.com/web3-storage/w3up/blob/main/packages/filecoin-client/src/dealer.js#L58
- https://github.com/web3-storage/w3up/blob/main/packages/filecoin-api/src/aggregator/service.js#L97
So, `AggregatorRecord` now has a property for buffer and one for pieces. `buffer` allows us to get to know the pieces inside the `buffer` while `pieces` is the direct encoding of `PieceLink[]` dag-cbor. We could just rely on the buffer, but for issuing all `aggregate/accept` receipts for each piece, we would need an extra S3 get to read the buffer and compute the dag cbor for the list of pieces inside the buffer
=> fix: aggregate offer invocation cid wrong

packages/w3up-client/test/client.test.js
This was previously released with old version of `upload-client`, so still using old PieceCIDv2 🤦🏼 
see https://github.com/web3-storage/w3up/pull/1011/files#diff-25fd91ace9b7aae0918c2010deea96d0cf07d0e7407973e2dc54efbc326d6dd4R7
=> fix: trigger commit for release of w3up client

packages/filecoin-api/src/storefront/api.ts, packages/filecoin-api/src/storefront/events.js, packages/filecoin-api/src/storefront/service.js, packages/filecoin-api/test/events/storefront.js, packages/filecoin-api/test/services/storefront.js, packages/filecoin-api/test/storefront.spec.js, packages/filecoin-api/test/types.ts, packages/upload-api/src/lib.js, packages/upload-api/test/helpers/context.js
Per https://github.com/web3-storage/w3filecoin-infra/issues/52 make storefront now same signer as aggregator to enable receipt chain
=> fix: enable storefront signer to be different from main service signer

packages/access-client/src/agent-use-cases.js, packages/capabilities/src/index.js, packages/capabilities/src/types.ts, packages/capabilities/src/usage.js, packages/capabilities/test/capabilities/usage.test.js, packages/did-mailto/package.json, packages/filecoin-api/package.json, packages/upload-api/package.json, packages/upload-api/src/lib.js, packages/upload-api/src/types.ts, packages/upload-api/src/types/usage.ts, packages/upload-api/src/usage.js, packages/upload-api/src/usage/report.js, packages/upload-api/test/handlers/plan.js, packages/upload-api/test/handlers/usage.js, packages/upload-api/test/handlers/usage.spec.js, packages/upload-api/test/helpers/context.js, packages/upload-api/test/lib.js, packages/upload-api/test/storage/plans-storage.js, packages/upload-api/test/storage/usage-storage.js, packages/upload-api/tsconfig.json, packages/upload-client/src/types.ts, packages/upload-client/test/helpers/mocks.js, packages/w3up-client/src/capability/usage.js, pnpm-lock.yaml
Adds a capability allowing agents to request a usage report for a given period.
The report includes the size of the space at the start of the period and at the end of the period, and additionally the events that caused the space to change size. This should allow us to display current storage usage for a space as well as graph space size change over time.
=> feat: add usage/report capability

packages/upload-api/src/provider-add.js, packages/upload-api/src/types.ts, packages/upload-api/test/handlers/provider-add.spec.js, packages/upload-api/test/helpers/context.js
We need this to ship billing, to stop users without a payment provider plan from provisioning new spaces.
I've added a flag to the `ProviderServiceContext` that lets us disable this requirement - this is extremely useful in testing and will be helpful as we roll this feature out - ie, w3infra can disable this requirement until we are ready to launch.
=> feat: optionally require plans for provisioning

packages/access-client/package.json
export paths were changed here: https://github.com/web3-storage/w3up/pull/1059/files#diff-c35cf4a2177e2a86b0f923b4a1682ad2b0344301cffc4f98053a82a1a47d6c1bR28
to point to JS files in the `src` directory, but per the `files` config further down we don't ship those files (and I don't think we should, since it would be duplicative)
=> fix: fix export paths for JS files

packages/capabilities/src/filecoin/index.js, packages/capabilities/src/filecoin/lib.js, packages/capabilities/src/filecoin/storefront.js, packages/capabilities/src/index.js, packages/capabilities/src/types.ts, packages/filecoin-api/src/errors.js, packages/filecoin-api/src/storefront/api.ts, packages/filecoin-api/src/storefront/service.js, packages/filecoin-api/test/context/receipts.js, packages/filecoin-api/test/context/store.js, packages/filecoin-api/test/events/storefront.js, packages/filecoin-api/test/services/storefront.js, packages/filecoin-api/test/storefront.spec.js, packages/filecoin-client/src/storefront.js, packages/filecoin-client/src/types.ts, packages/filecoin-client/test/helpers/mocks.js, packages/filecoin-client/test/storefront.test.js, packages/upload-api/test/helpers/context.js, packages/w3up-client/README.md, packages/w3up-client/package.json, packages/w3up-client/src/capability/filecoin.js, packages/w3up-client/src/client.js, packages/w3up-client/src/service.js, packages/w3up-client/src/types.ts, packages/w3up-client/test/capability/filecoin.test.js, packages/w3up-client/test/helpers/car.js, packages/w3up-client/test/helpers/mocks.js, packages/w3up-client/test/helpers/random.js, packages/w3up-client/test/test.js, pnpm-lock.yaml
Goal of the PR is to make filecoin deals information available for end users via client (and later on CLI + console). For this:
- adds `filecoin/info` capability to `capabilities`, `filecoin-api` and `filecoin-client`
- user can give the `piece` that was computed while uploading the file, or that was published via content claims
- exposes via `w3up-client` some filecoin sugar `*.filecoin.offer` and `*.filecoin.info` 
Note that `filecoin.info` only returns effective deals. Alternatively, user could ask directly dealTracker, even though user would need to know the aggregate where their piece was included. So, better make storefront facilitate user life with this shortcut
Would be great to actually give more information of the on going state, but I am failing to find a nice way of giving …
=> feat: filecoin info

packages/access-client/src/access.js, packages/access-client/src/agent-use-cases.js, packages/access-client/src/types.ts, packages/capabilities/src/customer.js, packages/capabilities/src/index.js, packages/capabilities/src/plan.js, packages/capabilities/src/provider.js, packages/capabilities/src/subscription.js, packages/capabilities/src/types.ts, packages/capabilities/src/utils.js, packages/upload-api/src/subscription.js, packages/upload-api/src/subscription/list.js, packages/upload-api/src/types.ts, packages/upload-api/src/types/subscriptions.ts, packages/upload-api/test/handlers/subscription.js, packages/upload-api/test/handlers/subscription.spec.js, packages/upload-api/test/handlers/usage.js, packages/upload-api/test/helpers/context.js, packages/upload-api/test/lib.js, packages/upload-api/test/storage/subscriptions-storage.js, packages/upload-api/test/util.js, packages/w3up-client/package.json, packages/w3up-client/src/capability/subscription.js, packages/w3up-client/src/capability/usage.js, packages/w3up-client/src/client.js, packages/w3up-client/test/capability/subscription.test.js, packages/w3up-client/test/capability/usage.test.js, packages/w3up-client/test/helpers/mocks.js, packages/w3up-client/test/helpers/utils.js
Invoking `subscription/list` will retrieve a list of subscriptions for a given account. The list of subscriptions allows us to discover spaces (consumers) that are owned (paid for) by the account. With the list of owned spaces we can make calls to `usage/report` to retrieve and display usage information.
~~TODO: add test to fix coverage in `w3up-client`~~
=> feat: add `subscription/list` capability

packages/w3up-client/README.md, packages/w3up-client/src/client.js, packages/w3up-client/test/client-accounts.test.js
Adds a `accounts()` method on the `Client` that allows users to list accounts they are logged into.
=> feat: expose accounts list on client instance

packages/w3up-client/src/client.js
This fixes type information on `client.capability.x` and adds the ability to use them separately.
=> fix: export new subscription, usage and filecoin clients

packages/w3up-client/src/account.js
currently we're unable to refer to the Account type, this fixes that
=> feat: export Account so we can use it in w3ui

packages/access-client/package.json, packages/capabilities/package.json, packages/upload-api/package.json, pnpm-lock.yaml
we discovered an issue with exponential performance degradation under certain circumstances in @ucanto/validator - upgrade the dependency to get the fix
=> fix: upgrade @ucanto/validator with bugfix

packages/access-client/package.json, pnpm-lock.yaml
Motivation:
* https://github.com/web3-storage/w3up/issues/1154
=> fix: access-client package.json uses https instead of git for one-webcrypto dep to help with yarn compat

package.json, packages/access-client/package.json, packages/capabilities/package.json, packages/did-mailto/package.json, packages/eslint-config-w3up/package.json, packages/filecoin-api/package.json, packages/filecoin-client/package.json, packages/upload-api/package.json, packages/upload-client/package.json, packages/w3up-client/package.json, pnpm-lock.yaml
the most critical here is the w3up-client metadata points to the old archived repo, which is confusing.
the rest of the changes are for consistency.
License: MIT
=> fix: package metadata

.github/release-please-config.json
adding `chore` commits to releases ensures that we have the option of cutting a release from a chore if we want to. with this change release PRs are created after landing any one of chore,fix,feat commit to main.
json schema for release-please config is here: https://github.com/googleapis/release-please/blob/cae5ac0a0203032726a3893bdafe7bde378ae27d/schemas/config.json#L31C10-L31C28
and the per repo config we used in the old monorepo is: https://github.com/web3-storage/web3.storage/blob/ca8b25c3a9466c081dcb3ab9cde733a9567c1c61/.github/workflows/client.yml#L56
License: MIT
=> chore: show chores in release notes

README.md
its better if we direct folks to the docs or the workshopper rather than try and explain it all here.
License: MIT
=> docs: simplify the readme js code example

packages/access-client/src/agent.js
@juliangruber reported an issue with our documented space creation flow when the exported space access delegation doesn't specify a name and the client doesn't specify one manually:
https://github.com/web3-storage/w3up/issues/1175
I think it's reasonable to require a name for spaces at some level, but I think the access-client API is too low-level for this.
=> fix: don't error when we can't figure out a name for a space

packages/w3up-client/src/account.js, packages/w3up-client/src/capability/subscription.js, packages/w3up-client/src/capability/usage.js, packages/w3up-client/src/client.js, packages/w3up-client/src/space.js, packages/w3up-client/src/types.ts, packages/w3up-client/test/account.test.js, packages/w3up-client/test/space.test.js
This PR allows you to get a list of subscriptions for your account plan, and also get the current per space usage (I've not exposed the full report yet since we don't have any UI that would use it).
e.g.
Getting subscriptions list:
```js
const account = Object.values(client.accounts())[0]
const subs = await account.plan.subscriptions()
for (const sub of subs.ok) {
console.log(`ID: ${sub.subscription}`)
console.log(`Consumers: ${sub.consumers.join(', ')}`)
console.log(`Provider: ${sub.provider}`)
}
```
Getting usage:
```js
const space = client.spaces()[0]
const usage = await space.usage.get()
console.log(`${space.did()}: ${usage.ok} bytes`)
```
So, you no longer have to invoke capabilities directly like this:
https://github.com/web3-storage/w3cli/blob/ca21f6736fb8c2180d3634f40931b91e4f0bb96 …
=> feat!: account plan subscriptions and space usage API sugar

packages/filecoin-api/src/aggregator/api.ts, packages/filecoin-api/src/aggregator/buffer-reducing.js, packages/filecoin-api/src/aggregator/events.js, packages/filecoin-api/test/events/aggregator.js, packages/filecoin-api/test/services/aggregator.js
Conveniently store the timestamp of the oldest piece in table, so that when monitoring aggregates time to deal for alerts, we do not need to read buffer, decode it, and find out it every time a CRON runs.
=> feat: aggregator keeping oldest piece ts

packages/capabilities/src/types.ts, packages/filecoin-api/src/storefront/events.js, packages/filecoin-api/src/storefront/service.js, packages/filecoin-api/test/events/aggregator.js, packages/filecoin-api/test/services/storefront.js, packages/filecoin-client/test/storefront.test.js, packages/w3up-client/test/capability/filecoin.test.js
This PR changes the output of `filecoin/info` such that aggregate information (piece CID and inclusion proof) are moved out of deal info. This means that aggregate info can be accessed before any deals are made and there is no repetition of inclusion proofs in each deal an aggregate is found in.
=> feat: move aggregate information out of deals in filecoin/info

.github/workflows/access-client.yml, .github/workflows/capabilities.yml, .github/workflows/did-mailto.yml, .github/workflows/filecoin-api.yml, .github/workflows/filecoin-client.yml, .github/workflows/upload-api.yml, .github/workflows/upload-client.yml, .github/workflows/w3up-client.yml, packages/access-client/src/agent.js, packages/access-client/src/space.js, packages/access-client/test/agent-data.test.js, packages/access-client/test/agent.test.js, packages/access-client/test/stores/store-indexeddb.browser.test.js, packages/did-mailto/test/did-mailto.spec.js, packages/eslint-config-w3up/index.js, packages/eslint-config-w3up/tsconfig.json, packages/upload-api/test/access-client-agent.js, packages/upload-api/test/handlers/plan.js, packages/upload-api/test/handlers/provider-add.spec.js, packages/upload-client/test/store.test.js, packages/w3up-client/test/capability/filecoin.test.js, packages/w3up-client/test/capability/space.test.js, packages/w3up-client/test/capability/store.test.js, packages/w3up-client/test/capability/upload.test.js, packages/w3up-client/test/client.test.js
Motivation:
* i want https://typescript-eslint.io/rules/no-floating-promises/
* it would have caught a floating promise on `addSpace` that alan just reported
=> feat: add to eslint-config-w3up no-floating-promises error

packages/access-client/src/agent.js
space names are stored as facts in proofs in the special `ucan:*` delegation from email to agent e.g.
```yaml
iss: did:mailto:protocol.ai:oli
att:
- can: *
with: ucan:*
fct:
- {"access/confirm":{"/":"bafyreidadrwbxueiuhtbph2tj2m7a6nizpx7sbtqotbfkkjsoytn3dg2t4"},"access/request":{"/":"bafyreigmlliovbpxka2borbdaw6zpsai4qzmzv5nv7syl7nagecxjcub6e"}}
prf:
- {"iss":"did:key:z6Mku56ywWspVnzkcVQbeSkw6egVRSNKVSYgS38HhKcUJRiN","aud":"did:mailto:protocol.ai:oli","v":"0.9.1","s":{"/":{"bytes":"7aEDQPgUVQFVOoLmijx8O7Li9zyc7iIHEDnCwiqr+LcV9CyHd/KzUg1Ige7Okh+ipVMOKy2EvG8dGjWfsdAAbUVPMwo"}},"exp":null,"att":[{"can":"*","with":"did:key:z6Mku56ywWspVnzkcVQbeSkw6egVRSNKVSYgS38HhKcUJRiN"}],"fct":[{"space":{"name":"fruits"}}],"prf":[],"/":"bafyreihhlz5yjci6h7vdrlgn5xnyc65e3unp3dx2yrspepwoftaxszxpxa"}
```
this …
=> fix: sync space names from proofs

packages/w3up-client/README.md
branchname s/trip/trim/
Motivation:
* https://github.com/web3-storage/w3up/issues/1215
=> docs: w3up-client README replace links to old tsdoc with links to correct/new tsdoc from monorepo

packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/upload-client/test/index.test.js
Motivation:
* @Gozala suggested it to help debug
* allow callers to opt into piece generation, and it's disabled by default (until we can ensure it'll work well for huge files)
* we may not keep this, but it could be helpful to allow `w3 up` to be used to upload huge files without the piece link calculation (in case it is erroring or taking too much memory)
=> feat: upload-client funcs have options.piece to opt in to piece link calculation

packages/upload-client/package.json, pnpm-lock.yaml
Previously `parallel-transform-web` was running up to N transform tasks concurrently, but while those tasks were running it buffered the rest of the stream data internally 🤦 .
This was resolved in https://github.com/alanshaw/parallel-transform-web/pull/1 so just pulling in the latest code here.
I was seeing memory usage in w3cli for a 12GB file grow to ~10GB but now it stays at around at round ~4GB (which is the same usage I see when I remove `parallel-transform-web` and replace it with a regular serial `TransformStream`).
=> fix: memory usage

packages/capabilities/src/types.ts, packages/eslint-config-w3up/index.js, packages/filecoin-api/test/events/aggregator.js, packages/upload-api/src/admin/store/inspect.js, packages/upload-api/src/admin/upload/inspect.js, packages/upload-api/src/store/add.js, packages/upload-api/src/store/get.js, packages/upload-api/src/store/lib.js, packages/upload-api/src/store/list.js, packages/upload-api/src/store/remove.js, packages/upload-api/src/types.ts, packages/upload-api/src/upload/add.js, packages/upload-api/src/upload/get.js, packages/upload-api/src/upload/lib.js, packages/upload-api/src/upload/list.js, packages/upload-api/src/upload/remove.js, packages/upload-api/test/handlers/store.js, packages/upload-api/test/handlers/upload.js, packages/upload-api/test/helpers/result.js, packages/upload-api/test/storage/store-table.js, packages/upload-api/test/storage/upload-table.js, packages/upload-client/test/index.test.js, packages/upload-client/test/store.test.js, packages/w3up-client/test/capability/store.test.js, packages/w3up-client/test/capability/upload.test.js, packages/w3up-client/test/client.test.js
This PR adds a new field to the `store/add` success result: `allocated: number` - the total bytes allocated in the space to accommodate the stored item, it **may be zero if the item is _already_ stored in _this_ space**.
This allows us to accurately report and bill for items stored in a space. Currently, `store/add` when the item is already stored in the space will cause a new diff to be created, effecitvely counting the same shard multiple times. This could happen because of accidentally uploading the same item, or because of a retry of a big item where some shards were successful.
The following additional changes enable this functionality:
* `StoreTable` and `UploadTable` methods now have return types that are `Result<O, X>` - this allows us to specify and communicate 2 errors …
=> feat!: return allocated bytes in `store/add` receipt

packages/access-client/package.json, packages/access-client/src/utils/json.js, packages/access-client/test/stores/store-conf.node.test.js
I made a change to use ArrayBuffers in AgentDataExport, which was not supported by our JSON.stringify function. Tweak the stringify replacer to handle this cleanly and add a test to verify it works as expected.
=> fix: support storing ArrayBuffers in conf

packages/w3up-client/package.json, packages/w3up-client/src/delegation.js, packages/w3up-client/tsconfig.json
I ran into an issue in a Next.js app that seems to be a result of having sourcecode and type declarations in separate directories:
```
./node_modules/.pnpm/@web3-storage+w3up-client@11.2.1/node_modules/@web3-storage/w3up-client/src/types.ts:15:29
Type error: Could not find a declaration file for module './client.js'. '/Users/travis/dev/pl/fetch-test/node_modules/.pnpm/@web3-storage+w3up-client@11.2.1/node_modules/@web3-storage/w3up-client/src/client.js' implicitly has an 'any' type.
13 |   Unit,
14 | } from '@ucanto/interface'
> 15 | import { type Client } from './client.js'
|                             ^
```
Copying the sourcecode into `dist` and updating exports to point to it seems to fix this.
=> fix: copy src into dist in w3up-client

packages/upload-client/package.json, packages/upload-client/src/fetch-with-upload-progress.js, packages/upload-client/src/store.js, packages/upload-client/src/types.ts, packages/upload-client/test/store.test.js
because importing it in bundled setups breaks, e.g.
* https://github.com/web3-storage/w3up/issues/1183
* https://github.com/web3-storage/w3up/issues/828
I tested this change locally and confirmed that once it's made, upload-client can be relied on by a nextjs project and build successfully
=> feat: dont use ipfs-utils fetch with upload progress by default 

packages/upload-client/src/store.js
This makes the assigned fetch behave a bit differently than a regular `globalThis.fetch`. a globalThis.fetch will sometimes fail if you do `const me = { fetch }; await me.fetch(url)` but now this bound one won't and will instead behave differently than `globalThis.fetch`.
I think the difference in behavior doesn't matter too much because we just use the assigned fetch right away without passing it along or calling it in such a way that we'd change the default behavior of function calling where `this` is `globalThis` in a way that all `fetch` i've encountered can work with.
=> fix: bind globalThis.fetch to globalThis

packages/access-client/package.json, packages/upload-client/package.json
`main` was pointing at `src/index.js` but `src` isn't included in the built package per the `files` key in `package.json`. Fix this!
=> fix: point `main` at files included in the package

packages/access-client/src/space.js, packages/access-client/src/types.ts, packages/w3up-client/src/types.ts
Not having these available as types is making it hard to build the web console space creation wizard.
=> feat: expose OwnedSpace and SharedSpace from access-client

packages/w3up-client/package.json
This PR adds `engines` and `engineStrict` props to the `package.json` ensuring users are running the lower bound of what we're currently testing on in CI (v18) when installing.
=> feat: strictly require nodejs version

README.md
Add a section about https://github.com/web3-storage/add-to-web3 to the main readme for discovery.
License: MIT
=> docs: add add-to-web3 to the main readme

packages/w3up-client/README.md
update to match changes from https://github.com/web3-storage/www/pull/72
Fixes https://github.com/web3-storage/www/issues/63
=> fix: update "byo agent" example to match website snippet

packages/w3up-client/README.md, packages/w3up-client/src/client.js, packages/w3up-client/test/client.test.js
This PR adds high level function for removing to the client. It essentially follows what has been done in the CLI https://github.com/web3-storage/w3cli/blob/main/index.js#L189-L237
We currently provide this feature according to the docs https://web3.storage/docs/how-to/remove/#using-the-js-client-or-cli but it is not there.
It is annoying that we have docs for something that does not exist. Other option would be to change the docs to use low level capabilities, even though that means explaining more to the users what shards are, which I think is not the best direction. 
Two discussion points:
- Not performing this in an atomic operation may lead to inconsistencies, where for instance part of the shards could be removed but then other operations fail... This is also the current behaviour …
=> feat: add remove high level function to client

packages/w3up-client/README.md, packages/w3up-client/package.json, packages/w3up-client/src/stores.js, packages/w3up-client/src/stores/conf.js, packages/w3up-client/src/stores/index.js, packages/w3up-client/src/stores/indexeddb.js, packages/w3up-client/src/stores/memory.js
`stores.js` was importing code that uses nodejs modules and is not bundleable....
refs https://github.com/web3-storage/w3up/issues/1274#issuecomment-1907561703
=> fix: allow import memory store in the browser

packages/capabilities/src/types.ts, packages/upload-api/src/plan.js, packages/upload-api/src/types/plans.ts, packages/upload-api/test/handlers/plan.js, packages/upload-api/test/storage/plans-storage-tests.js, packages/upload-api/test/storage/plans-storage.js
We need a way to initialize an account's "plan" with information about the product the user has selected and an billing ID used by the billing system.
Add this and more tests that demonstrate how it is expected to be used.
=> feat: add `initialize` method to `PlansStorage`

packages/capabilities/src/types.ts, packages/upload-api/package.json, packages/upload-api/src/types/plans.ts, packages/upload-api/test/storage/plans-storage-tests.js, packages/upload-api/test/storage/plans-storage.js
Introduce `UnexpectedError` to allow implementations to return errors that weren't anticipated in the interface definition.
More information about this problem here:
https://github.com/web3-storage/RFC/pull/7#issuecomment-1911245054
Also in this PR:
1) export plan.js as a module so callers can use error classes defined there 
2) use `prettier` to make things prettier
=> fix: one more tweak to the `PlanStorage` interface

packages/access-client/src/types.ts, packages/upload-api/src/types.ts
I'm getting tsc failures in `w3infra/upload-api` because access-client hasn't been updated to incorporate `UnexpectedError` - update access client types so we can ship a new version. While I'm here, add set method to upload-api `Service` type as well.
=> feat: two more interface tweaks

packages/upload-client/src/store.js, packages/w3up-client/README.md
Apparently some fetch implementations may not have "mode", which is the case for Cloudflare Workers for instance. CF worker deploying upload-client is now failing because this "mode" is set. You can also read more about the general problem in https://github.com/aws/aws-sdk-js-v3/issues/1165
In summary, "mode" may not be implemented in fetch, but the default appears to be cors anyway so this could be deleted without loss of functionality: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode#default_mode.
Related to https://github.com/web3-storage/w3up/issues/1273
=> fix: upload client does not need cors mode on presigned url put

packages/upload-client/package.json, pnpm-lock.yaml
Needs:
Closes https://github.com/web3-storage/w3up/issues/1273
=> fix: update fr32 lib to support wasm import

packages/filecoin-api/src/aggregator/api.ts, packages/filecoin-api/src/aggregator/buffer-reducing.js, packages/filecoin-api/src/aggregator/events.js, packages/filecoin-api/test/events/aggregator.js
We may need to at the implementation level inject pieces in the start of the Aggregate to overcome requirements of Boost when using PoDSI-formatted aggregate, where first bytes can be problematic for SP to grab in the start of the aggregate
This allows implementer to easily pass an array within the lambda context to run, and easily drop it when needed without being hardcoded in the actual lib :)
=> feat: add support to prepend pieces while buffering to aggregate

packages/access-client/package.json, packages/capabilities/package.json, packages/filecoin-api/package.json, packages/filecoin-client/package.json, packages/upload-api/package.json, packages/upload-client/package.json, packages/w3up-client/package.json, pnpm-lock.yaml
Motivation:
* get this commit in w3up packages https://github.com/web3-storage/ucanto/pull/342
=> feat: upgrade ucanto/transport to 9.1.0 in all packages to get more verbose errors from HTTP transport on non-ok response

packages/upload-client/package.json, packages/upload-client/src/index.js, packages/upload-client/src/types.ts, pnpm-lock.yaml
Allows users to bring their own piece hasher. i.e. they can use the faster [fr32-sha2-256-trunc254-padded-binary-tree-multihash](https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash) hasher if their environment allows them to load the WASM.
Switches the client to use the JS implementation by default.
refs https://github.com/web3-storage/w3up/issues/1322
=> feat: byo piece hasher

packages/upload-api/package.json
Adds some exports that were missing:
=> fix: missing exports

packages/upload-client/package.json, packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/upload-client/test/helpers/filecoin.js, packages/upload-client/test/helpers/mocks.js, packages/upload-client/test/index.test.js, packages/upload-client/tsconfig.json, packages/w3up-client/test/client.test.js, packages/w3up-client/test/helpers/filecoin.js, packages/w3up-client/tsconfig.json, pnpm-lock.yaml
In context of https://github.com/w3s-project/project-tracking/issues/25 and https://github.com/web3-storage/w3infra/issues/344 we set the client to perform filecoin/offer already so that new users, as well as users that upgrade in the meantime can already perform this, in order to better prepare us to get rid of bucket event
=> fix: upload client should perform filecoin offer

packages/filecoin-api/package.json, packages/filecoin-api/src/aggregator/buffer-reducing.js, packages/filecoin-api/src/aggregator/events.js, packages/filecoin-api/src/errors.js, packages/filecoin-api/src/storefront/api.ts, packages/filecoin-api/src/storefront/events.js, packages/filecoin-api/src/storefront/piece.js, packages/filecoin-api/src/storefront/service.js, packages/filecoin-api/src/types.ts, packages/filecoin-api/test/context/mocks.js, packages/filecoin-api/test/context/service.js, packages/filecoin-api/test/context/store-implementations.js, packages/filecoin-api/test/context/store.js, packages/filecoin-api/test/context/types.ts, packages/filecoin-api/test/events/aggregator.js, packages/filecoin-api/test/events/storefront.js, packages/filecoin-api/test/storefront.spec.js, packages/filecoin-api/test/types.ts, packages/filecoin-api/test/utils.js, pnpm-lock.yaml
This PR hooks up possibility to compute Piece CID when submit message is received.
For extra context, today w3infra sets `skipFilecoinSubmitQueue` on `filecoin/offer` from users, resulting `filecoin/offer` in a noop that simply links receipts for effects of `filecoin/submit` and `filecoin/accept`. This is due to the API to not care about what was submit by client as it is calculated in bucket event anyway. However, we want to change this behaviour to have filecoin pipeline only triggered on `filecoin/offer`, putting it in the submit queue where validation will now happen.
We can summarise these changes in two units:
- `handleFilecoinSubmitMessage` now reads data from store, computes piece CID for the bytes and checks equality with provided Piece (i.e. bucket event code …
=> feat: api waits for trigger filecoin pipeline from the client

packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/upload-client/test/index.test.js
It's sometimes useful to disable piece hashing, if only for debugging. JS destructuring makes this easy to enable - if someone passes a piece hasher or null we use that (and don't do piece hashing if it's null) and if someone doesn't pass a piece hasher we fall back to PieceHasher.
=> feat: make it possible to disable piece hashing

package.json, packages/w3up-client/src/capability/upload.js, pnpm-lock.yaml
I was seeing some strange errors in the nft.storage work I'm doing right now and realized it's a result of a copypasta bug in `upload-client` where we query for the wrong capability when putting together this invocation.
We missed this in testing because tests use one big proof, which means that asking for `upload/add` is equivalent to asking for `upload/get` - in an ideal world I'd spend a bit of time untangling this but since I'm at the bottom of a stack of shaved yaks I'd like to get this shipped and file an issue to come back to this later.
=> fix: look for the correct capability in `client.capability.upload.get`

packages/upload-api/package.json
Need errors exported to use in storage implementations for infra
=> fix: add errors to exports

packages/capabilities/src/index.js
Another small fix, just add exports on capabilities for blob caps
=> fix: capabilities should export blob caps

packages/access-client/src/access.js
Client needs `blob/*` capabilities in order to invoke `blob/add`
=> fix: access client should request blob namespace capabilities

packages/upload-api/src/blob/allocate.js, packages/upload-api/src/types/blob.ts, packages/upload-api/test/storage/allocations-storage-tests.js, packages/upload-api/test/storage/allocations-storage.js
Per https://github.com/web3-storage/w3infra/pull/353#discussion_r1570092934 renaming this to cause so that it is transparent for the infra side what this is: i.e. can be invocation or receipt
=> fix: allocation interface rename invocation to cause

packages/filecoin-api/src/storefront/api.ts, packages/filecoin-api/src/storefront/service.js
This is not needed since https://github.com/web3-storage/w3up/pull/1332 got released and used in w3infra https://github.com/web3-storage/w3infra/pull/343 and has been deployed in production without issues for the last few weeks
BREAKING CHANGE: not possible to skip submit queue on storefront service anymore
=> fix!: drop filecoin storefront skip submit queue option

.github/workflows/manual.yml, .github/workflows/release.yml, .github/workflows/reusable-deploy-docs.yml, packages/access-client/package.json, packages/capabilities/package.json, packages/did-mailto/package.json, packages/eslint-config-w3up/package.json, packages/filecoin-api/package.json, packages/filecoin-client/package.json, packages/upload-api/package.json, packages/upload-client/package.json, packages/w3up-client/package.json
- CI was failing because the nested job didn't get what it needed;
- Addressed NPM provenance.
=> fix: migrate repo

.github/workflows/release.yml
We're getting a `Error creating Pull Request: Not Found` aka a 404 which to me signals some auth issue. More [here](https://github.com/w3s-project/w3up/actions/runs/8804910171/job/24166333991).
Other repos such as [content-claims](https://github.com/w3s-project/content-claims/blob/main/.github/workflows/release.yml#L28) don't use this and are working properly.
=> fix: remove unneeded token

packages/capabilities/package.json, packages/capabilities/readme.md, packages/capabilities/src/index.js, packages/capabilities/src/index/index.js, packages/capabilities/src/types.ts, packages/capabilities/test/capabilities/index.test.js, packages/upload-api/src/types/blob.ts
Adds `index/add` capability.
refs https://github.com/w3s-project/specs/blob/main/w3-index.md
BREAKING CHANGE: `BlobMultihash` type in `@web3-storage/capabilities` renamed to `Multihash`.
=> feat(capabilities)!: add `index/add` capability

packages/filecoin-api/src/storefront/api.ts, packages/filecoin-api/src/storefront/events.js, packages/filecoin-api/src/storefront/piece.js, packages/filecoin-api/src/types.ts, packages/filecoin-api/test/context/store-implementations.js, packages/filecoin-api/test/context/store.js, packages/filecoin-api/test/context/types.ts, packages/filecoin-api/test/events/storefront.js, packages/filecoin-api/test/storefront.spec.js, packages/filecoin-api/test/types.ts
With the aim to facilitate https://github.com/w3s-project/w3up/issues/1349 storefront `dataStore` is renamed to `contentStore` (note alignment of name with the `content` property in Filecoin Pipeline capabilities/message namings). My goal is to make `contentStore.stream()` perform HTTP Request to read thing from Roundabout (if `filecoin/offer` comes with `content` CARCID code, it will try to get a CAR, if `content` comes as RAW, it will try to get RAW).
The main point in this change is to not require `contentStore` to have a `put` method, like `dataStore` was requiring just for testing. It extracts that requirement only to run tests, so that we can implement a `contentStore` as something with just a `stream` function that behind the scenes can perform a HTTP Request to Roundabout instead …
=> fix!: storefront content store rename and separation for test

packages/capabilities/src/store.js, packages/capabilities/src/types.ts, packages/capabilities/test/capabilities/store.test.js, packages/upload-api/src/types.ts, packages/upload-api/test/handlers/space-info.spec.js, packages/upload-api/test/handlers/store.js, packages/upload-client/src/store.js, packages/w3up-client/src/capability/store.js
Restricts store API to CARs per our decision.
=> feat!: restrict store API to CARs

packages/upload-api/src/blob/accept.js, packages/upload-api/test/handlers/web3.storage.js, pnpm-lock.yaml
Specifier ensures only the single raw block is served by the gateway. It is not a DAG, it's a single block of content.
=> fix: add format specifier to blob location claim URL

packages/upload-api/src/store/add.js, packages/upload-api/src/types.ts
This is based on #1344 and it stops passing issuer when inserting into a table. I wanted to make this a separate PR so we can update w3infra first and remove field there and then stop passing here.
=> feat: remove issuer row

packages/upload-api/src/types.ts
Per https://github.com/web3-storage/w3up/issues/1339#issuecomment-2015852195 this PR deprecates `issuer` field from table record.
=> feat!: deprecate issuer

packages/upload-client/src/index.js
As we previously decided, `filecoin/offer` should receive raw CIDs https://github.com/w3s-project/w3up/issues/1408#issuecomment-2082091981 so that everything works out of the box and Blobs can be read from roundabout for validation + from SPs
=> fix: cid for filecoin offer must be raw

packages/capabilities/src/blob.js, packages/capabilities/src/index/index.js, packages/capabilities/src/utils.js, packages/capabilities/test/capabilities/index.test.js, packages/filecoin-api/src/errors.js, packages/filecoin-api/test/context/service.js, packages/filecoin-api/test/context/store-implementations.js, packages/filecoin-api/test/services/aggregator.js, packages/filecoin-api/test/services/storefront.js, packages/filecoin-api/test/types.ts, packages/upload-api/src/lib.js, packages/upload-api/src/space.js, packages/upload-api/src/space/info.js, packages/upload-api/src/types.ts, packages/upload-api/test/handlers/web3.storage.js, packages/upload-api/test/storage/blobs-storage-tests.js, packages/upload-api/test/storage/blobs-storage.js, packages/upload-client/src/types.ts, packages/upload-client/test/blob.test.js, packages/upload-client/test/dag-index.test.js, packages/upload-client/test/helpers/mocks.js, packages/upload-client/test/index.test.js, packages/w3up-client/test/ability.test.js
Rename capabilities to minimize issues on migration for clients based on https://github.com/w3s-project/RFC/pull/12
=> fix: rename blob and index client capabilities

packages/filecoin-api/package.json, packages/upload-api/package.json, packages/upload-api/src/blob/accept.js, packages/upload-api/test/handlers/web3.storage.js, pnpm-lock.yaml
This upgrades the content-claims dependency, allowing us to use multihash digest in location claim. It brings implementation in line with the spec.
=> feat: use digest in `blob/accept` location commitment

packages/w3up-client/src/client.js
Allows `client.capability.blob` to be typed.
=> fix: export blob client

packages/capabilities/src/blob.js, packages/capabilities/src/types.ts, packages/upload-api/src/blob.js, packages/upload-api/src/blob/accept.js, packages/upload-api/src/blob/get.js, packages/upload-api/src/types.ts, packages/upload-api/src/types/blob.ts, packages/upload-api/test/handlers/web3.storage.js, packages/upload-client/src/blob.js, packages/upload-client/src/types.ts, packages/upload-client/test/blob.test.js, packages/upload-client/test/helpers/mocks.js, packages/w3up-client/src/capability/blob.js, packages/w3up-client/test/capability/blob.test.js
Adds support for `blob/get` as defined in https://github.com/w3s-project/specs/pull/126
=> feat: add blob/get

packages/upload-client/src/blob.js, packages/upload-client/test/blob.test.js, packages/upload-client/test/helpers/receipts-server.js, packages/upload-client/test/helpers/utils.js
From @vasco-santos:
1. if we already have a http/put receipt, we should not send one
2. if we already receive in next a blob accept receipt, we should not await on the receipt generation
=> fix: reuse http/put and blob/accept receipts when available

packages/w3up-client/package.json, packages/w3up-client/src/client.js, packages/w3up-client/src/delegation.js, packages/w3up-client/src/principal/ed25519.js, packages/w3up-client/src/principal/index.js, packages/w3up-client/src/principal/rsa.js, packages/w3up-client/src/proof.js, packages/w3up-client/test/proof.test.js
This PR re-exports some ucanto exports and a utility function to parse a proof (in any current or legacy format). This should make working with the client easier as all the things you need are available (no additional deps to install), makes the docs much more succinct and easier to follow, and actually allows you to import a base64 encoded delegation successfully from any period in time you obtained it.
Here's one of many code snippets from the docs site that will be improved by this PR:
```js
import * as Client from '@web3-storage/w3up-client'
import { StoreMemory } from '@web3-storage/w3up-client/stores/memory'
import { importDAG } from '@ucanto/core/delegation'
import { CarReader } from '@ipld/car'
import * as Signer from '@ucanto/principal/ed25519'
async function main () {
// Load …
```
=> feat: utility exports for better UX

packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/upload-client/src/unixfs.js, packages/upload-client/test/unixfs.test.js, packages/w3up-client/src/client.js, packages/w3up-client/src/types.ts
This allows a UnixFS DAG to be encoded that uses v0 CIDs.
I don't really want to encourage this, but the alternative is asking users to build their own DAGs, encode their own CAR and then pass it to `uploadCAR`.
=> feat: configure UnixFS encoder

packages/filecoin-api/src/storefront/service.js
This was causing the following error in production:
```
2024-06-21T04:05:01.605Z	ee3a792e-71d8-4188-9a45-a3f44a153719	WARN	HandlerExecutionError: service handler {can: "filecoin/info"} error: Cannot read properties of undefined (reading 'aggregate')
at invoke (/node_modules/@ucanto/server/src/server.js:157:21)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at run (/node_modules/@web3-storage/upload-api/src/lib.js:169:10)
... 4 lines matching cause stack trace ...
at processResult (/node_modules/src/awslambda.ts:326:50) {
capability: {
nb: {
piece: CID(bafkzcibdyuhqqhgb72e23rtoielekn2lsknb4naxhvyz6fhsd7bms4ld6ghbaiqi)
},
can: 'filecoin/info',
with: 'did:key:z6MkiBeiHFA6kbA2mchg1F9juxCuHuLgymzJpanKswpBZmQT'
},
cause: TypeError: Cannot read properties of …
```
=> fix: return piece accept receipt error

packages/filecoin-api/package.json, packages/filecoin-api/src/aggregator/api.ts, packages/filecoin-api/src/aggregator/service.js, packages/filecoin-api/src/deal-tracker/api.ts, packages/filecoin-api/src/deal-tracker/service.js, packages/filecoin-api/src/dealer/api.ts, packages/filecoin-api/src/dealer/events.js, packages/filecoin-api/src/storefront/api.ts, packages/filecoin-api/src/storefront/events.js, packages/filecoin-api/src/types.ts, packages/filecoin-api/test/context/store-implementations.js, packages/filecoin-api/test/context/store.js, packages/filecoin-api/test/context/types.ts, packages/filecoin-api/test/events/aggregator.js, packages/filecoin-api/test/events/dealer.js, packages/filecoin-api/test/events/storefront.js, packages/filecoin-api/test/services/aggregator.js, packages/filecoin-api/test/services/deal-tracker.js, packages/filecoin-api/test/services/dealer.js, packages/filecoin-api/test/services/storefront.js, pnpm-lock.yaml
This PR updates filecoin-api to add pagination to the query interfaces. Currently only the first page of results is returned.
This means in the fileocin pipeline cron jobs we never process more than 1 page of items, even though there are sometimes many more items to process and ample execution time remaining in the lambda.
If only the first page of items is processed it gives a false sense of everything operating ok, when actually things may be backing up. It essentially smothers the issue. If the lambda times out because there are too many items to process then this is a good indication that it needs some attention.
Essentially, the interface changes from:
```ts
interface Queryable<Q, T> {
query (q: Q): Promise<Result<T[]>>
}
```
To this:
```ts
interface Pageable {
cursor?: string
size?: …
```
=> feat(filecoin-api): paginated queries

package.json, packages/access-client/package.json, packages/blob-index/package.json, packages/capabilities/package.json, packages/did-mailto/package.json, packages/filecoin-api/package.json, packages/filecoin-client/package.json, packages/upload-api/package.json, packages/upload-client/package.json, packages/w3up-client/package.json
Now `pnpm dev` will watch and build all packages in one terminal!
=> chore: Add `pnpm dev` to watch-build all packages

packages/upload-client/test/helpers/receipts-server.js, packages/upload-client/test/helpers/utils.js
It's not obvious that the mocks need to be running for tests to run. Now the output will warn you and tell you how to run them.
=> chore: Warn if mocks aren't running

packages/upload-client/src/car.js, packages/upload-client/src/types.ts
Should return a `ReadableStream<Uint8Array>`, not a `ReadableStream<any>`. Get it straight from `Blob` to be sure it matches.
This bit me while trying to work with the API.
=> refactor: `BlobLike`'s `stream()` matches `Blob`'s

.github/workflows/w3up-client.yml, packages/w3up-client/README.md, packages/w3up-client/src/client.js, packages/w3up-client/test/client-accounts.test.js, packages/w3up-client/test/client.test.js
Issue https://github.com/storacha-network/project-tracking/issues/124
The [`space.create(name, options)`](https://github.com/storacha-network/w3cli/blob/3f59da7b096a63f14def9946682160fefacd0702/space.js#L24) function in `space.js`  allows the user to pass the following options:
- **recovery**: `false` (default)
- **caution**: `false` (default)
- **customer**: `Email | false`
- **account**: `string | false`
If the `account` attribute is provided, the following steps are triggered:
1. `space.createdRecovery` is called.
2. Then, `client.capabilities.access.delegate` is executed.
This process occurs during **space creation**, not during provisioning.  
Provisioning only happens when the `customer` attribute is provided in the `options` argument.
---
The …
=> feat(client): optional account recovery

packages/w3up-client/README.md, packages/w3up-client/src/account.js, packages/w3up-client/test/account.test.js
This PR introduces a new `wait()` method to the `AccountPlan` class, which simplifies the process of waiting for a payment plan to be selected. By integrating configurable polling intervals, timeouts, and abort signals, the method abstracts the common logic required in this scenario, making it easier for developers to implement and customize their workflows.
- **New `wait()` Method**:
- The `wait()` method repeatedly checks the account's payment plan status at a given interval until:
- A valid plan is selected.
- The timeout is reached.
- The operation is aborted using an `AbortSignal`.
- Available options:
- `interval` (default: 1000ms): Sets the polling interval.
- `timeout` (default: 15 minutes): Defines the maximum wait time.
- `signal`: An optional `AbortSignal` to allow for …
=> feat: wait for plan selection

.github/workflows/access-client.yml, .github/workflows/blob-index.yml, .github/workflows/capabilities.yml, .github/workflows/did-mailto.yml, .github/workflows/filecoin-api.yml, .github/workflows/filecoin-client.yml, .github/workflows/manual.yml, .github/workflows/release.yml, .github/workflows/upload-api.yml, .github/workflows/upload-client.yml
Apparently this is not needed when `packageManager` is set in root `package.json`.
=> fix: remove redundant package manager version

README.md, packages/access-client/package.json, packages/access-client/readme.md, packages/access-client/src/agent.js, packages/blob-index/README.md, packages/blob-index/package.json, packages/blob-index/src/api.ts, packages/capabilities/package.json, packages/capabilities/readme.md, packages/capabilities/src/access.js, packages/capabilities/src/ucan.js, packages/did-mailto/package.json, packages/eslint-config-w3up/package.json, packages/filecoin-api/package.json, packages/filecoin-client/README.md, packages/filecoin-client/package.json, packages/filecoin-client/src/aggregator.js, packages/filecoin-client/src/deal-tracker.js, packages/filecoin-client/src/dealer.js, packages/filecoin-client/src/storefront.js, packages/upload-api/README.md, packages/upload-api/package.json, packages/upload-client/README.md, packages/upload-client/package.json, packages/w3up-client/README.md, packages/w3up-client/package.json, tsconfig.json
Fixes a _lot_ of old repo URLs e.g.`w3s-project` and `web3.storage`
Needs a follow up PR to remove references to reference docs site that does not exist: `web3-storage.github.io`
I'd like to use [jsr](https://jsr.io/) for this somehow!
=> fix: repo URLs

packages/w3up-client/src/client.js, packages/w3up-client/test/client.test.js
This PR introduces a new `shareSpace()` method that allows users to delegate access to an existing space with another Storacha account via email. This feature enhances collaboration by enabling multiple accounts to share access to a space, making data sharing more flexible.
By default, the following capabilities/permissions are set:
- space/* - for managing space metadata
- store/* - for managing stores
- upload/*- for registering uploads
- access/* - for re-delegating access to other devices
- filecoin/* - for submitting to the filecoin pipeline
- usage/* - for querying usage
- **Added `shareSpace()` Method**:
- The `shareSpace()` method allows users to share an existing space with another Storacha account by delegating access to the specified email address.
- The method takes in the …
=> feat: sharing spaces

packages/filecoin-api/package.json, packages/filecoin-api/src/aggregator/api.ts, packages/filecoin-api/src/aggregator/buffer-reducing.js, packages/filecoin-api/src/aggregator/events.js, pnpm-lock.yaml
This PR updates `@web3-storage/data-segment` and passes a custom sha256 hashing function through to the aggregate builder.
=> feat(filecoin-api): allow custom hashing function to be passed to aggregate builder

packages/access-client/src/agent-data.js
This was deprecated in https://github.com/storacha/w3up/pull/433, but it's still what we use, and no clear migration path was given.
@alanshaw Do you remember what the plan was? Should we do this and reverse it, or is there a better way we should write down?
=> refactor: De-deprecate `AgentData`'s `addSpace()`

packages/access-client/src/agent-use-cases.js, packages/capabilities/src/top.js, packages/upload-api/src/access/claim.js, packages/upload-api/src/access/confirm.js, packages/upload-api/src/types.ts, packages/upload-api/test/access-client-agent.js, packages/upload-api/test/types.ts
The bulk of the work for https://github.com/storacha/project-tracking/issues/125.
This together with [`w3ui` calling `access/claim` on page load](https://github.com/storacha/w3ui/pull/644) will make new spaces appear on the page without logging out.
---
* On `access/confirm`, where we previously created a `*`/`ucan:*` delegation with proofs for each space, we now create one with no proofs. This delegation technically provides no capability, but serves as a signal in `access/claim`.
* During `access/claim`, we look for the Agent's `*`/`ucan:*` delegations in the store, and translate them on the fly into ones containing proofs for the relevant spaces. This is legitimate, because `*`/`ucan:*` means the Agent has been granted access to anything the Account can do, it just doesn't have the …
=> feat: Generate Space proofs on the fly, on `access/claim`

packages/filecoin-api/src/aggregator/events.js
Simply uses `p-map` to put items to the queue in parallel and speed up execution time of this lambda (which is currently timing out).
=> fix(filecoin-api): parallel put to piece accept queue

.github/workflows/access-client.yml, .github/workflows/blob-index.yml, .github/workflows/did-mailto.yml, .github/workflows/filecoin-api.yml, .github/workflows/upload-api.yml, .github/workflows/w3up-client.yml, packages/access-client/src/space.js
* `space.signer.withDID(account)` gives us a Signer with the Space's key, but which reports the Account's DID. It looks like this might have been needed at some point when this thing was actually used to sign something. But as of now, we don't need a *Signer*, just a DID, and a `did:mailto:` is fine. So, simplify this.
* This was being passed as the `agent`, but it's not an Agent. `createAuthorization()` doesn't need an Agent, it needs an *audience*. In some cases that's an Agent, in some cases it's an Account. This changes the name to clarify.
=> refactor: Avoid conflation of Space and Account

packages/upload-api/test/access-client-agent.js
**Resolve ESLint Promise Handling Error**
Fixed the ESLint error by using `assert.rejects` to handle the promise returned by `deviceCheater.setCurrentSpace`. This ensures that the promise is properly managed and the test checks for expected rejections, addressing the ESLint rule that requires promises to be awaited, handled with `.catch`, or explicitly ignored.
=> fix(test): await promise and check error

packages/filecoin-api/package.json, packages/filecoin-api/src/aggregator/api.ts, packages/filecoin-api/src/aggregator/buffer-reducing.js, packages/filecoin-api/src/aggregator/events.js, packages/filecoin-api/test/events/aggregator.js
In lambda we only have 15 minutes max to execute. Without significant changes to the way the library works there is only so many hashes we can perform.
This PR adds a new configuration parameter `maxAggregatePieces` which serves to restrict the maximum number of hashes the aggregator will have to perform to build an aggregate. This will be tuned to be as high as possible to allow execution within the time bounds. The PR also adds logging in order to determine this limit.
=> fix: configure max pieces

.attw.json, .gitignore, packages/w3up-client/.gitignore, packages/w3up-client/README.md, packages/w3up-client/package.json, pnpm-lock.yaml
This PR adds a pre-built browser bundle.
Importing the bundle will add a `w3up` variable to the global context which contains all the exports from the client library.
=> feat: add pre-built browser bundle

packages/capabilities/src/space.js, packages/upload-api/src/space/record.js
This PR fixes the handling of the `servedAt` timestamp in the `packages/upload-api/src/space/record.js` file. 
The previous implementation included a multiplication by 1000, assuming a conversion from seconds to milliseconds was necessary. This change removes the conversion.
=> fix(egressRecord): Remove unnecessary multiplication for ts conversion

packages/upload-api/package.json, packages/upload-api/src/blob/accept.js, packages/upload-api/src/types.ts, packages/upload-api/test/handlers/blob.js, packages/w3up-client/test/capability/space.test.js, pnpm-lock.yaml
Big oversight here, although I think the original intention was to have the client publish these so perhaps not.
Anyways, since no location claims are being published the gateway cannot fetch an index and serve bytes quickly. It has to get a location claim for every single block using the old dynamodb. Being able to use the index will result in a speed increase for serving content via the gateway.
Depends on https://github.com/storacha/content-claims/pull/74 for passing tests.
=> fix: publish location claim to content claims service

packages/upload-client/src/sharding.js, packages/upload-client/test/sharding.test.js
In the unusual case where a sharding stream has to create a new shard because adding the root CID to the CAR header pushes it over the shard limit the slice indexing info for the new shard was set for the blocks in the previous shard, not the blocks in the new shard 🤦, this means that one or more blocks in DAG were not indexed at all.
=> fix: overflow slices

packages/capabilities/src/types.ts, packages/filecoin-api/src/aggregator/events.js, packages/filecoin-api/test/context/service.js, packages/upload-api/src/access/claim.js, packages/upload-api/src/lib.js, packages/upload-api/test/helpers/utils.js, packages/w3up-client/src/client.js, packages/w3up-client/src/index.js, packages/w3up-client/src/types.ts, packages/w3up-client/test/account.test.js, packages/w3up-client/test/capability/access.test.js, packages/w3up-client/test/capability/blob.test.js, packages/w3up-client/test/capability/filecoin.test.js, packages/w3up-client/test/capability/index.test.js, packages/w3up-client/test/capability/space.test.js, packages/w3up-client/test/capability/store.test.js, packages/w3up-client/test/capability/subscription.test.js, packages/w3up-client/test/capability/upload.test.js, packages/w3up-client/test/capability/usage.test.js, packages/w3up-client/test/client.test.js, packages/w3up-client/test/coupon.test.js, packages/w3up-client/test/mocks/service.js, packages/w3up-client/test/space.test.js
To enable a gateway to serve content from a specific space, we must ensure that the space owner delegates the `space/content/serve/*` capability to the Gateway. This delegation allows the Gateway to serve content and log egress events appropriately.
I created a new function `authorizeContentServe` for this implementation and included it in the `createSpace` flow. This is a breaking change because now the user is forced to provide the DIDs of the Content Serve services, and the connection, or skip the authorization flow.
Additionally, with the `authorizeContentServe` function, we can implement a feature in the Console App that enables users to explicitly authorize the Freeway Gateway to serve content from existing/legacy spaces.
- **New Functionality:** Added a new function, …
=> feat!: content serve authorization

packages/upload-client/src/blob/add.js, packages/upload-client/test/blob.test.js
FML, we have a useless retry function that does not retry the PUT request when fetch response is non-200.
Not any more.
=> fix: retry when PUT request fails

packages/capabilities/package.json, packages/capabilities/src/filecoin/index.js, packages/capabilities/src/filecoin/storefront.js, packages/capabilities/src/types.ts, packages/w3up-client/src/client.js
- Added the Filecoin top-level capability.
- Updated w3up-client to use it instead of defining all of the filecoin capabilities.
Resolves: https://github.com/storacha/w3up/issues/1554
=> chore(capabilities): top level filecoin cap

packages/w3up-client/package.json, packages/w3up-client/src/account.js, packages/w3up-client/src/client.js, packages/w3up-client/test/client.test.js, packages/w3up-client/test/helpers/gateway-server.js, packages/w3up-client/test/mocks/service.js
While updating the `web3-storage` docs, `w3cli`, and `@storacha/client`, I found it inconvenient to repeatedly define the gateway DID and URL every time I created a space. Also, if we don't provide the `skipGatewayAuthorization=true`, it will throw an error saying it is required to provide the gateway services to authorize.
Following @travis suggestion (see: https://github.com/storacha/docs/pull/21#discussion_r1883075639), I've updated the client to automatically authorize the Storacha Gateway (Production) by default if `skipGatewayAuthorization` is not set to `true` and `authorizeGatewayServices` is not provided or is empty.
Once approved, this change will need to be ported to [upload-service/w3up-client](https://github.com/storacha/upload-service/tree/main/packages/w3up-client).
And the …
=> feat(w3up-client): add default gateway authorization

packages/w3up-client/src/client.js
We need to save the space before setting it as the current space, otherwise the authorization flow will fail because the agent won't be allowed to use that space.
=> fix(w3up-client): authorize agent to use space

packages/w3up-client/src/client.js
- The `options` argument in the `createSpace` method should be optional, so we don't have a breaking change.
- Updated the Gateway URL to use the public one.
=> fix(w3up-client): options in createSpace should be optional

packages/access-client/package.json, packages/access-client/src/crypto/encoding.js, packages/filecoin-api/package.json, packages/upload-api/package.json, packages/upload-api/test/util.js, packages/upload-client/package.json, packages/upload-client/test/helpers/car.js, pnpm-lock.yaml
all tests pass, the change is 100% backwards compatible.
Improves deduplication when using other ipfs-* related packages. For example ipfs-car depends on ipfs-unixfs@3, while w3up still depended on v2
=> chore: upgrade dependencies for better de-duplication

packages/access-client/src/access.js, packages/capabilities/src/access.js, packages/filecoin-api/src/aggregator/buffer-reducing.js, packages/filecoin-api/src/aggregator/events.js, packages/filecoin-api/test/context/store-implementations.js, packages/filecoin-api/test/events/aggregator.js, packages/upload-api/src/access/authorize.js, packages/upload-api/src/blob/accept.js, packages/upload-api/src/types.ts, packages/upload-api/src/types/usage.ts, packages/upload-api/test/handlers/blob.js, packages/w3up-client/src/account.js, packages/w3up-client/src/capability/access.js, packages/w3up-client/src/types.ts
refs https://github.com/storacha/RFC/pull/43
This PR adds a new method `externalLogin()` that allow login to the system via an external method (e.g. OAuth). It essentially bypasses email confirmation, assuming this is done out of band. We re-join the regular auth flow at the point when we claim the delegation (and attestation) from an email to the agent.
=> feat: external login

packages/access-client/src/agent.js, packages/access-client/test/agent.test.js
closes https://github.com/storacha/w3up/issues/1633
backporting here this fix: https://github.com/storacha/upload-service/pull/143
=> fix: dedupe proofs

packages/access-client/src/types.ts, packages/upload-api/src/access/authorize.js, packages/upload-api/src/validate.js, packages/w3up-client/src/types.ts
Ports over the upload api changes in the above commit to upload service
-- original commit message
feat: add `app` to `access/authorize` and `access/confirm` (#264) (
We need a way to ensure users are redirected back to `https://bsky.storage` after completing the Stripe checkout process.
To facilitate this, pass facts from `access/authorize` to`access/confirm` - users can now add a fact like `{app: 'bsky-backups'}` to `access/authorize`, which will tell the `access/confirm` handling code in `w3infra` to render the same pricing table we use on https://bsky.storage which sends the user back to that app after picking a plan via the email flow.
Add support for this to the client code via a new `appName` option in the account creation functions that gets converted to a fact at the lowest …
=> feat: port of https://github.com/storacha/upload-service/commit/2c12c23d13d14e9f1b79c34b8169f20975d431f7
