package.json, packages/api/package.json, packages/api/src/abilities/access.js, packages/api/src/bindings.d.ts, packages/api/src/index.js, packages/api/src/utils/context.js, packages/api/src/utils/responses.js, packages/api/src/utils/ucan-router.js, packages/api/test/api.test.js, packages/api/test/helpers/setup.js, packages/api/test/ucan.test.js, packages/api/wrangler.toml, pnpm-lock.yaml
=> feat: ucan endpoint

packages/access-api/package.json, packages/access-api/src/ucanto/server-codec.js, packages/access-api/src/utils/context.js, packages/access-api/test/ucan.test.js, pnpm-lock.yaml
Implement support for https://github.com/ucan-wg/ucan-as-bearer-token
Diff:
- we support multiple invocations
- cache and expiry header not implemented yet 
Cant really understand https://github.com/ucan-wg/ucan-as-bearer-token#22-ucan-by-cid-table
=> feat: support ucan as bearer

packages/access/src/index.js, packages/access/src/types.ts
We should be able to stop the polling!
=> feat: abortable pullRegisterDelegation

packages/access/src/connection.js
=> fix: temporary patch to allow fetch usage in browser

packages/access-api/src/routes/validate.js
this might be all we need to close #71
=> redirect on success

packages/access/src/capabilities/identity.js
Fixes regression introduces by #79
=> fix: regression from `store -> all` name change

packages/access/test/capabilities/store.test.js, packages/access/test/capabilities/upload.test.js
Adding more tests just to ensure this is accurate https://github.com/web3-storage/ucanto/issues/87
=> chore: add ns/* tests

readme.md
=> fix: Document deployment procerss and URLs #100

spec/sequences/participants.md, spec/sequences/registration.md, spec/sequences/todo.md, spec/sequences/upload-and-list.md
I think these will require more than one round of feedback, so it probably makes sense to merge them more or less as is, if the file layout makes sense and they should be in this repository.
Then we can do additional refinement in PRs to the markdown files.
=> sequence diagrams: registration, upload, and list

packages/access-api/scripts/cli.js
It wasnt starting the http server.
=> fix: miniflare dev script

packages/upload-client/src/store.js, packages/upload-client/src/upload.js
Per https://github.com/web3-storage/w3protocol/actions/runs/3524498570/jobs/5910005524
=> fix: upload client list needs empty nb

packages/upload-client/package.json, packages/upload-client/src/store.js, packages/upload-client/src/types.ts, packages/upload-client/src/upload.js, packages/upload-client/test/store.test.js, packages/upload-client/test/upload.test.js
=> feat: support pagination

packages/access-client/src/agent.js
Ported change from https://github.com/web3-storage/w3protocol/pull/207/files#diff-69a4efe733b2d7920dc103a0370eb1a285403e39c41e1b5e9a0718ea66b5a32fR445
=> fix: add proof of voucher redeem

packages/access-api/wrangler.toml
Motivation:
* @hugomrdias told me
=> fix: access-api wrangler.toml sets DID env var in env.dev

packages/access-api/readme.md, packages/access-api/scripts/cli.js
Related to https://github.com/web3-storage/w3protocol/issues/112
=> chore(access-api): add docs about sourcemaps

packages/access-api/src/service/index.js, packages/access-api/src/service/upload-api-proxy.js, packages/access-api/src/ucanto/proxy.js, packages/access-api/test/ucanto-proxy.test.js
Motivation:
* part of #325 
* remove things that were only useful for debugging/prototyping
=> chore: remove parts of access-api/src/service.js upload-api-proxy that were only useful for debugging/testing

readme.md
=> docs: fix typos

packages/upload-client/src/types.ts
per the change in https://github.com/web3-storage/w3infra/pull/139, add startCursor and endCursor and deprecate cursor
=> feat: add startCursor and endCursor to ListResponse

packages/access-api/src/utils/email.js
per https://github.com/web3-storage/w3protocol/issues/341
I've already set up DKIM and Return-Path in postmark, all that's left is to push this change to production:
=> feat: send emails from noreply@web3.storage

.github/workflows/access-api.yml
Motivation:
* resolve https://github.com/web3-storage/w3protocol/issues/496
=> ci: remove deploy-dev from .github/workflows/access-api.yml

packages/access-api/test/access-client-agent.test.js, packages/access-client/src/agent-use-cases.js, packages/access-client/src/agent.js
Expose authorizeWithSocket and ……authorizeWithPollClain and authorizeAndWait
=> feat: get rid of Promise.race in authorize.

packages/access-client/src/agent.js
otherwise the account will eventually lose access to the space
=> fix: don't let space delegation proofs expire

packages/access-api/src/routes/validate-email.js, packages/access-api/src/service/access-authorize.js, packages/access-api/src/service/access-confirm.js, packages/access-api/test/access-client-agent.test.js, packages/access-client/src/agent-use-cases.js, packages/access-client/src/agent.js, packages/access-client/src/utils/ws.js
Motivation:
* review comments on https://github.com/web3-storage/w3protocol/pull/433
=> chore: 433 bengo review comments

packages/access-client/src/agent.js
this is not ideal, but I chatted with @gozala and we agreed that this makes sense for now
=> fix: only use spaces with key dids

package.json, pnpm-lock.yaml
We have [discussed this in the past](https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1663361102233959) and everyone was onboard except one opponent who no longer contributes to the project.
It still gets in my way so I propose we remove the hook, if we find that it was a mistake we can always revert it.
=> chore: remove pre-commit hook

package.json, packages/access-api/package.json, packages/access-api/src/models/delegations.js, packages/access-api/src/models/provisions.js, packages/access-api/src/types/access-api-cf-db.ts, packages/access-api/src/utils/d1.js, pnpm-lock.yaml
Motivation:
* https://github.com/web3-storage/w3protocol/pull/578/files#r1144141609
=> chore: upgrade kysely-d1 and clean up db-related things due to d1 lib upgrades

packages/access-api/src/models/delegations.js, packages/access-api/src/types/access-api-cf-db.ts, packages/access-api/test/delegations-storage.test.js
Motivation:
* part of https://github.com/web3-storage/w3protocol/pull/578
=> fix: DbDelegationsStorageWithR2 saving to desired r2 key

packages/access-api/src/service/index.js
Motivation:
* https://github.com/web3-storage/w3protocol/issues/608
* unblock testing against prod
=> feat: remove checks that disable some access/ functionality in prod

packages/access-api/test/snapshots/README.md
see https://github.com/web3-storage/w3protocol/pull/640
this didn't get published as was `chore`.
see also #642 
License: MIT
=> fix: release changes to email validation confirmation page

packages/access-api/src/utils/html.js
=> fix: center email validation layout

.github/release-please-config.json
now that we've released a new version in https://github.com/web3-storage/w3protocol/pull/589
=> chore: unpin capabilities

packages/w3up-client/src/capability/access.js, packages/w3up-client/src/client.js
=> feat: add capabilities option type for authorize

.github/release-please-config.json
Motivation:
* try to fix https://github.com/web3-storage/w3up/issues/694
=> ci: release-please-config sets bootstrap sha

packages/w3up-client/src/space.js
Motivation:
* dummy commit to test #694 
* I expect when we merge this, I want to see release-please open a w3up-client release-please PR for 5.5.1
=> fix: add newline to space.js to test release-please 694 fix

packages/access-api/src/index.js
Motivation:
* #623 - see if errors from this show up different than errors from ucanto HandlerExceptionError
=> fix: add /.debug/error route

.github/release-please-config.json, .github/release-please-manifest.json
aggregate-api release please PR is still not being created
=> fix: release please manifest for aggregate api and aggregate client

packages/upload-api/src/access/claim.js, packages/upload-api/src/access/confirm.js, packages/upload-api/src/access/delegate.js, packages/upload-api/src/customer/get.js, packages/upload-api/src/provider-add.js, packages/upload-api/src/types.ts, packages/upload-api/src/types/delegations.ts, packages/upload-api/src/types/provisions.ts, packages/upload-api/src/utils/email.js, packages/upload-api/test/delegations-storage-tests.js, packages/upload-api/test/delegations-storage.js, packages/upload-api/test/delegations-storage.spec.js, packages/upload-api/test/helpers/context.js, packages/upload-api/test/lib.js, packages/upload-api/test/provisions-storage-tests.js, packages/upload-api/test/provisions-storage.js, packages/upload-api/test/provisions-storage.spec.js, pnpm-lock.yaml
Noticed while working on aggregate-api and client that format/lint is failing for `upload-api`. So ran format for it in different branch to put fix it in main without creating noise in other PR
=> fix: run format for upload-api

packages/access-client/src/drivers/memory.js, packages/access-client/src/index.js, packages/access-client/src/stores/store-memory.js
Adding an in-memory driver for use in serverless environments
=> feat: In-Memory Driver

packages/capabilities/src/types.ts, packages/upload-api/src/types/provisions.ts, packages/upload-api/test/provisions-storage.js
talked to @alanshaw about this here and we agreed this is a much less confusing name: https://github.com/web3-storage/w3infra/pull/220/files#r1301646148
=> feat: change "total" to "limit"

packages/access-client/src/agent.js
something seems to have gone wrong with release-please and the latest release doesn't have the latest code. bump the version to fix this, and improve docs at the same time.
=> fix: update docs to bump version

packages/filecoin-api/test/services/dealer.js
=> fix: dealer test

packages/filecoin-client/README.md
They were not updated with last release of the client
=> docs: update filecoin client docs

packages/access-client/src/types.ts, packages/w3up-client/test/capability/space.test.js
=> fix: add providers to space/info result type

packages/filecoin-api/src/dealer.js, packages/filecoin-api/src/types.ts, packages/filecoin-api/test/services/dealer.js, packages/upload-api/src/space.js, packages/upload-api/src/types/provisions.ts, packages/upload-api/test/access-authorize.js, packages/upload-api/test/access-client-agent.js, packages/upload-api/test/provisions-storage-tests.js, packages/upload-api/test/provisions-storage.js, packages/upload-api/test/upload.js
ran `pnpm format`, checked in result
=> chore: format

packages/upload-api/test/lib.js
mostly pushing this in order to trigger a release - I incorrectly called my previous commit a `chore`
=> feat: reorg tests

packages/upload-api/src/admin/store/inspect.js, packages/upload-api/src/admin/upload/inspect.js, packages/upload-api/src/types.ts, packages/upload-api/test/handlers/store.js, packages/upload-api/test/handlers/upload.js, packages/upload-api/test/storage/store-table.js, packages/upload-api/test/storage/upload-table.js
per PR feedback here: https://github.com/web3-storage/w3infra/pull/225#issuecomment-1723968093
=> feat: rename getCID to inspect

packages/access-client/package.json, packages/capabilities/package.json, packages/capabilities/src/types.ts, packages/filecoin-client/package.json, packages/upload-client/package.json, packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/w3up-client/package.json, pnpm-lock.yaml
Fixes [top level await](https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1695053425167059) problem by upgrading playwright-test. I also fixed a some type mismatches causing typecheck to fail
=> fix: top level await error

packages/access-client/package.json, packages/capabilities/package.json, packages/capabilities/src/types.ts, packages/filecoin-client/package.json, packages/upload-client/package.json, packages/upload-client/src/index.js, packages/upload-client/src/types.ts, packages/w3up-client/package.json, pnpm-lock.yaml
Currently blocked on top level await issue.
=> refactor: switch to rust piece CID calculator

.vscode/settings.json
realllllly thought I removed this
=> chore: back out settings.json

packages/filecoin-api/src/aggregator/service.js, packages/filecoin-api/src/dealer/service.js, packages/filecoin-api/src/storefront/events.js, packages/filecoin-api/src/storefront/service.js, packages/filecoin-api/test/context/store.js
Per https://github.com/web3-storage/w3filecoin/pull/55#discussion_r1372841961
=> fix: filecoin api store has returns false

packages/filecoin-api/src/dealer/events.js, packages/filecoin-api/test/events/dealer.js
Per https://github.com/web3-storage/w3filecoin/pull/60#discussion_r1375953327
=> fix: typo dealer event function name

packages/filecoin-api/src/dealer/api.ts, packages/filecoin-api/src/dealer/events.js, packages/filecoin-api/src/dealer/service.js, packages/filecoin-api/test/context/store-implementations.js, packages/filecoin-api/test/dealer.spec.js, packages/filecoin-api/test/events/dealer.js, packages/filecoin-api/test/services/dealer.js
Otherwise, we need to have deal in the table
=> fix: aggregate accept should rely on deal tracker response to issue receipt

packages/upload-client/package.json, packages/upload-client/src/index.js, pnpm-lock.yaml
per https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash/issues/24
=> feat: upgrade fr32-sha2-256-trunc254-padded-binary-tree-multihash for async hasher

packages/filecoin-api/src/dealer/events.js, packages/filecoin-api/test/events/dealer.js
Removes space making new names as `2023-09-23T15:49:50.437Z_bafkzcibbdyuvfiycundi3xfjuzpuilhsijzf7ryp63tlsczf464zlwieujdqg.json`
=> fix: dealer offer store keys without space

packages/filecoin-api/src/storefront/api.ts, packages/filecoin-api/src/storefront/events.js, packages/filecoin-api/src/storefront/service.js, packages/filecoin-api/test/events/storefront.js, packages/filecoin-api/test/services/storefront.js, packages/filecoin-api/test/storefront.spec.js, packages/filecoin-api/test/types.ts, packages/upload-api/src/lib.js, packages/upload-api/test/helpers/context.js
This reverts commit 21ded3c171ca66480e4f74329943527dcc2bac3e **(#1072)**
=> fix: revert enable storefront signer to be different from main service signer

packages/access-client/readme.md, packages/upload-client/README.md, packages/w3up-client/README.md
for some reason it didn't pick this up so hopefully this will help it get things straight
=> feat!: tweak readmes to get release-please to bump major version

packages/w3up-client/README.md
Remove mentions of beta and updates links.
=> docs: update readme

packages/w3up-client/src/account.js, packages/w3up-client/test/account.test.js
Logging with the same account several times creates and stores redundant proofs and then sends them over during invocations.
Changes here avoid this redundancy by returning an account using existing proofs if you already happen to have them, essentially making login idempotent.
=> fix: make login idempotent

packages/upload-client/package.json, pnpm-lock.yaml
=> fix: upgrade fr32-sha2-256-trunc-254-padded-binary-tree-multihash to 3.1.1.

packages/capabilities/src/plan.js, packages/capabilities/src/types.ts, packages/capabilities/test/capabilities/plan.test.js
We'd like to allow users to update their billing plans from console - introduce a new capability to enable this.
=> feat: introduce capability for changing billing plan

packages/w3up-client/README.md
1) add instructions on how to wait for a payment plan to be selected 
2) add space recovery setup instructions
=> fix: additional space setup steps

packages/upload-api/test/lib.js
Need these exported in order to test stores for w3infra
=> fix: export test handlers and storages

packages/upload-api/src/errors.js
See https://github.com/web3-storage/w3up/blob/main/packages/capabilities/src/types.ts#L530
=> fix: storage operation failed type name instead of store

packages/upload-api/src/types/service.ts, packages/upload-api/src/ucan/conclude.js, packages/upload-api/test/handlers/ucan.js, packages/upload-api/test/handlers/web3.storage.js
=> fix: ucan conclude scheduler invocation type and improve test

packages/upload-api/src/validate.js
Need to trigger a release to validate CI.
=> fix: add whitespace to trigger a release

packages/capabilities/src/utils.js
Try to make release action run
=> fix: trigger capabilities release

packages/filecoin-api/src/errors.js, packages/upload-api/src/blob/add.js, packages/upload-api/src/errors.js, packages/upload-api/test/storage/index.js, packages/upload-api/test/storage/usage-storage.js, packages/upload-client/src/blob.js, packages/upload-client/test/blob.test.js, packages/w3up-client/test/client.test.js
Fixes various issues to get tests passing
=> fix: blob add

packages/upload-client/package.json
Needs to be imported from integration tests and likely other places
=> fix: upload client export blob

packages/upload-client/src/index.js, packages/upload-client/test/index.test.js, packages/w3up-client/src/client.js, packages/w3up-client/test/client.test.js
As we did a release while not ready
=> fix: revert blob add by default

packages/upload-client/src/index.js, packages/upload-client/test/index.test.js, packages/w3up-client/src/client.js, packages/w3up-client/test/client.test.js
This reverts commit b77ec750c3911f6f47fa32a5e1560858b347985c.
To merge/release when ready
=> Revert "fix: revert blob add by default (#1456)"

packages/upload-api/src/blob/accept.js, packages/upload-api/src/types/blob.ts, packages/upload-api/test/handlers/ucan.js, packages/upload-api/test/handlers/web3.storage.js, packages/upload-api/test/storage/blobs-storage-tests.js, packages/upload-api/test/storage/blobs-storage.js
Ensures we don't hardcode the downlaod URL in the implementation.
=> feat!: add download URL method to `BlobsStorage`

package.json
[As in `console`.](https://github.com/storacha-network/console/pull/117)
=> chore: Add `packageManager` to `package.json`

packages/upload-api/src/provider-add.js
It's checking the `with` of the capability.
=> fix: Error should refer to Resource, not Issuer

packages/w3up-client/test/capability/usage.test.js
Trigger new release for `w3up-client` after merging related PRs for `capabilities`, `upload-api`, and `upload-client`.
=> feat: new release
